# Stage 1: Build
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

# Vite env vars are baked into the bundle at build time via `import.meta.env`
ARG VITE_HF_TOKEN
ARG VITE_GEMINI_API_KEY
ARG VITE_FIREBASE_API_KEY
ARG VITE_FIREBASE_AUTH_DOMAIN
ARG VITE_FIREBASE_PROJECT_ID
ARG VITE_FIREBASE_STORAGE_BUCKET
ARG VITE_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_FIREBASE_APP_ID
ARG VITE_FIREBASE_MEASUREMENT_ID

ENV VITE_HF_TOKEN=$VITE_HF_TOKEN
ENV VITE_GEMINI_API_KEY=$VITE_GEMINI_API_KEY
ENV VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY
ENV VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN
ENV VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID
ENV VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET
ENV VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID
ENV VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID
ENV VITE_FIREBASE_MEASUREMENT_ID=$VITE_FIREBASE_MEASUREMENT_ID

RUN echo "=== Build-time env check ===" \
    && echo "VITE_HF_TOKEN:                    ${VITE_HF_TOKEN:+[SET]}${VITE_HF_TOKEN:-[NOT SET]}" \
    && echo "VITE_GEMINI_API_KEY:              ${VITE_GEMINI_API_KEY:+[SET]}${VITE_GEMINI_API_KEY:-[NOT SET]}" \
    && echo "VITE_FIREBASE_API_KEY:            ${VITE_FIREBASE_API_KEY:+[SET]}${VITE_FIREBASE_API_KEY:-[NOT SET]}" \
    && echo "VITE_FIREBASE_AUTH_DOMAIN:        ${VITE_FIREBASE_AUTH_DOMAIN:+[SET]}${VITE_FIREBASE_AUTH_DOMAIN:-[NOT SET]}" \
    && echo "VITE_FIREBASE_PROJECT_ID:         ${VITE_FIREBASE_PROJECT_ID:+[SET]}${VITE_FIREBASE_PROJECT_ID:-[NOT SET]}" \
    && echo "VITE_FIREBASE_STORAGE_BUCKET:     ${VITE_FIREBASE_STORAGE_BUCKET:+[SET]}${VITE_FIREBASE_STORAGE_BUCKET:-[NOT SET]}" \
    && echo "VITE_FIREBASE_MESSAGING_SENDER_ID:${VITE_FIREBASE_MESSAGING_SENDER_ID:+[SET]}${VITE_FIREBASE_MESSAGING_SENDER_ID:-[NOT SET]}" \
    && echo "VITE_FIREBASE_APP_ID:             ${VITE_FIREBASE_APP_ID:+[SET]}${VITE_FIREBASE_APP_ID:-[NOT SET]}" \
    && echo "VITE_FIREBASE_MEASUREMENT_ID:     ${VITE_FIREBASE_MEASUREMENT_ID:+[SET]}${VITE_FIREBASE_MEASUREMENT_ID:-[NOT SET]}" \
    && npm run build

# Stage 2: Serve with nginx
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

# nginx config template — PORT is substituted at container startup
COPY nginx.conf.template /etc/nginx/conf.d/default.conf.template

# Railway sets $PORT at runtime; default to 8080 for local Docker runs
ENV PORT=8080
EXPOSE 8080

CMD sh -c "envsubst '\$PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
