import React, { useState, useEffect, useRef } from 'react';
import { Pin, Send, XCircle, Home, CheckSquare, Calendar, Lock, Key, Activity, Newspaper, ChevronDown, ChevronUp, Bell, Heart, Upload, LogOut, Sun, CloudRain, Wind, AlertCircle, Trash2, Edit2, Plus, Sword, Map, Settings, ShieldAlert, Sparkles, ChevronRight, MessageSquare, X, Download } from 'lucide-react';
import { AreaChart, Area, Tooltip, ResponsiveContainer } from 'recharts';
import ProfileDropdown from './ProfileDropdown';
import EditProfileModal from './EditProfileModal';
import EnvironmentWidget from './EnvironmentWidget';
import WellnessOdyssey from './WellnessOdyssey';
import { sendMessageToSParsh } from '../services/geminiService';
import { analyzeSentimentAndSchedule } from '../services/sentimentAgent';
import { Message, WellnessTask, AppointmentSlot, P2PMessage, ConsentData, User, WellnessPost } from '../types';
import ConsentForm from './ConsentForm';
import * as db from '../services/storage';
import { useSParsh } from '../contexts/SParshContext';
import { useNotification } from '../contexts/NotificationContext';
import OnboardingTour from './OnboardingTour';
import { getUser, updateUser } from '../services/storage';
import { useStorageSync } from '../hooks/useStorageSync';
import { COUNSELORS } from '../constants';

interface Props {
  triggerCrisis: () => void;
  userEmail: string;
  userId: string;
  user: User;
}

/** Generate a PDF for a confirmed consent */
const downloadConsentAsPDF = async (slotId: string) => {
  const consent = await db.getConsentForSlot(slotId);
  if (!consent) return;
  const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"/><title>Consent – ${consent.studentName}</title>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet"/>
  <style>@page{margin:24mm 20mm;}body{font-family:'Inter',sans-serif;font-size:13px;color:#222;line-height:1.7;}
  h1{font-size:18px;text-align:center;}.info{background:#f7f7f7;padding:12px;border-radius:6px;margin:12px 0;display:grid;grid-template-columns:1fr 1fr;gap:6px;border:1px solid #e0e0e0;}
  .sigs{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:20px;border-top:2px solid #e0e0e0;padding-top:16px;}
  .sig-box{border:1px solid #ccc;border-radius:6px;padding:12px;min-height:80px;}.footer{text-align:center;color:#aaa;font-size:10px;margin-top:24px;}
  </style></head><body>
  <h1>Informed Consent for Psychological Counseling</h1>
  <div class="info">
    <div><strong>Student:</strong> ${consent.studentName}</div>
    <div><strong>Counselor:</strong> ${consent.counselorName || 'Ms. Dimple Wagle'}</div>
    <div><strong>Slot ID:</strong> ${consent.slotId}</div>
    <div><strong>Date:</strong> ${new Date(consent.studentSignDate).toLocaleString()}</div>
  </div>
  <p>This consent confirms voluntary participation in psychological counselling at SPJIMR under the assigned counselor, subject to standard confidentiality protocols.</p>
  <div class="sigs">
    <div class="sig-box"><strong>Student Signature</strong><br/>${consent.studentSignature?.startsWith('data:image')
      ? `<img src="${consent.studentSignature}" style="max-height:60px;margin-top:4px;"/>`
      : `<p style="font-family:cursive;font-size:22px;">${consent.studentSignature || '—'}</p>`
    }<p style="font-size:11px;color:#666;">Date: ${new Date(consent.studentSignDate).toLocaleString()}</p></div>
    <div class="sig-box"><strong>Counselor Signature</strong><br/>
    <p style="font-family:cursive;font-size:22px;">${consent.counselorSignature || 'Pending'}</p>
    <p style="font-size:11px;color:#666;">Date: ${consent.counselorSignDate ? new Date(consent.counselorSignDate).toLocaleString() : 'Pending'}</p></div>
  </div>
  <p class="footer">Generated by SPeakUp | SPJIMR Mental Health Ecosystem</p>
  <script>window.onload=()=>window.print();</script>
  </body></html>`;
  const win = window.open('', '_blank');
  if (win) { win.document.write(html); win.document.close(); }
};

// ─── Wall Post Card ────────────────────────────────────────────────────────
const WallPostCard: React.FC<{ post: WellnessPost }> = ({ post }) => {
  const [expanded, setExpanded] = useState(false);
  const lines = post.body.split('\n');
  const isLong = lines.length > 5 || post.body.length > 400;
  const preview = isLong && !expanded ? post.body.slice(0, 380) + '…' : post.body;

  return (
    <div className={`rounded-2xl p-5 shadow-sm border ${post.isPinned ? 'bg-amber-50 border-amber-200' : 'bg-white border-slate-100'} transition-all`}>
      {post.isPinned && (
        <div className="flex items-center gap-1 text-amber-600 text-[11px] font-bold uppercase tracking-wider mb-2">
          <Pin size={11} /> Pinned
        </div>
      )}
      <h3 className="font-bold text-[#708090] text-base mb-1 leading-snug">{post.title}</h3>
      <p className="text-[11px] text-slate-400 mb-3">
        📝 {post.authorName} · {new Date(post.postedAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}
      </p>
      <div className="text-sm text-slate-600 leading-relaxed whitespace-pre-wrap">{preview}</div>
      {isLong && (
        <button
          onClick={() => setExpanded(v => !v)}
          className="mt-2 flex items-center gap-1 text-[#8A9A5B] text-xs font-bold hover:underline"
        >
          {expanded ? <><ChevronUp size={13} /> Show less</> : <><ChevronDown size={13} /> Read more</>}
        </button>
      )}
    </div>
  );
};

// ─── Main Dashboard ────────────────────────────────────────────────────────
const StudentDashboard: React.FC<Props> = ({ triggerCrisis, userEmail, userId, user: initialUser }) => {
  const { addNotification, storedNotifications, unreadCount, markAllRead, clearAll, clearOne } = useNotification();
  const [user, setUser] = useState<User>(initialUser);
  const [showEditProfileModal, setShowEditProfileModal] = useState(false);
  const { setVibe, setAvatarState } = useSParsh();

  const studentName = (() => {
    const namePart = userEmail.split('.')[1]?.split('@')[0];
    if (!namePart) return 'Student';
    return namePart.charAt(0).toUpperCase() + namePart.slice(1);
  })();

  const [activeTab, setActiveTab] = useState<'home' | 'tasks' | 'booking'>('home');
  const [isChatOpen, setIsChatOpen] = useState(false);
  const [messages, setMessages] = useState<Message[]>([]);
  const [inputText, setInputText] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isCloudSyncing, setIsCloudSyncing] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const [apiError, setApiError] = useState(false);
  const [showBellDropdown, setShowBellDropdown] = useState(false);
  const bellRef = useRef<HTMLDivElement>(null);

  const [tasks, setTasks] = useState<WellnessTask[]>([]);
  const [slots, setSlots] = useState<AppointmentSlot[]>([]);
  const [showConsentModal, setShowConsentModal] = useState(false);
  const [selectedSlot, setSelectedSlot] = useState<AppointmentSlot | null>(null);

  const [showP2P, setShowP2P] = useState(false);
  const [p2pMessages, setP2PMessages] = useState<P2PMessage[]>([]);
  const [p2pInput, setP2PInput] = useState('');

  // Wall feed posts
  const [posts, setPosts] = useState<WellnessPost[]>([]);

  // Wellness Odyssey overlay
  const [odyssey, setOdyssey] = useState<{ open: boolean; type: 'GAD7' | 'BDI' }>({ open: false, type: 'GAD7' });

  // Two-counselor selector
  const [selectedCounselor, setSelectedCounselor] = useState<typeof COUNSELORS[0] | null>(null);
  const [showCounselorPicker, setShowCounselorPicker] = useState(false);

  // Onboarding
  const [showOnboarding, setShowOnboarding] = useState(false);

  // Close bell dropdown on outside click
  // ── Real-time cross-tab sync (zero-latency, fires on every localStorage change in other tabs)
  useStorageSync(async (changedKey) => {
    if (changedKey.startsWith('speakup_cloud_slots')) {
      setSlots(await db.getSlots());
    }
    if (changedKey.startsWith('speakup_cloud_tasks')) {
      setTasks(await db.getTasks(userEmail));
    }
    if (changedKey.startsWith('speakup_cloud_posts')) {
      setPosts(await db.getAllPosts());
    }
    if (changedKey.startsWith('speakup_cloud_p2p') && showP2P && selectedCounselor) {
      setP2PMessages(await db.getP2PThread(userId, selectedCounselor.id));
    }
  });

  // ── Polling interval (fallback for same-tab updates and Safari)
  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (bellRef.current && !bellRef.current.contains(e.target as Node)) setShowBellDropdown(false);
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, []);

  // ── Load data on mount + 5-second polling (catches same-tab updates)
  useEffect(() => {
    // Check onboarding
    const hasSeenOnboarding = localStorage.getItem(`speakup_onboarding_${userId}`);
    if (!hasSeenOnboarding) {
      setShowOnboarding(true);
    }

    const loadData = async () => {
      setIsCloudSyncing(true);
      const [history, tasksData, slotsData, postsData] = await Promise.all([
        db.getChatHistory(userId),
        db.getTasks(userEmail),
        db.getSlots(),
        db.getAllPosts(),
      ]);
      setMessages(history);
      setTasks(tasksData);
      setSlots(slotsData);
      setPosts(postsData);
      setIsCloudSyncing(false);
    };
    loadData();
    const interval = setInterval(async () => {
      const [slotsData, postsData] = await Promise.all([db.getSlots(), db.getAllPosts()]);
      setSlots(slotsData);
      setPosts(postsData);
      if (showP2P) setP2PMessages(await db.getP2PThread(userId, 'counselor_dimple'));
    }, 5000);
    return () => clearInterval(interval);
  }, [userId, userEmail, showP2P]);

  const scrollToBottom = () => messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  useEffect(() => scrollToBottom(), [messages]);

  const handleCrisis = async () => {
    triggerCrisis();
    await db.sendP2PMessage({
      id: Date.now().toString(),
      senderId: 'system',
      receiverId: 'counselor_dimple_wagle',
      text: `🚨 EMERGENCY ALERT: ${studentName} (${userEmail}) triggered the SParsh Crisis Protocol. Immediate attention required.`,
      timestamp: new Date().toISOString(),
      isRead: false
    });
  };

  const processMessageSend = async (textToSend: string) => {
    setAvatarState('listening');
    setIsLoading(true);
    setApiError(false);

    const validHistory = messages.filter(m => !m.text.includes('Token Limit Reached'));
    const history = validHistory.map(m => ({ role: m.role === 'agent' ? 'model' : m.role, parts: [{ text: m.text }] }));

    const response = await sendMessageToSParsh(history, textToSend, true);

    setIsLoading(false);
    setAvatarState('speaking');

    if (response.text.includes('API key not valid') || response.text.includes('System Error')) setApiError(true);
    if (response.detectedMood) setVibe(response.detectedMood);
    if (response.isCrisis) await handleCrisis();

    const modelMsg: Message = { id: (Date.now() + 1).toString(), role: 'model', text: response.text, timestamp: new Date() };
    const updatedMessages = [
      ...validHistory,
      { id: Date.now().toString(), role: 'user', text: textToSend, timestamp: new Date() } as Message,
      modelMsg,
    ];
    setMessages(updatedMessages);
    setIsCloudSyncing(true);
    await db.saveChatMessage(userId, modelMsg);
    setIsCloudSyncing(false);

    analyzeSentimentAndSchedule(userId, userEmail, updatedMessages).then(async (agentMsg) => {
      if (agentMsg) {
        if (agentMsg.metadata?.type === 'crisis_trigger') await handleCrisis();
        if (agentMsg.metadata?.type === 'task_assignment') setTasks(await db.getTasks(userEmail));
        if (agentMsg.metadata?.type === 'booking_confirmation') setSlots(await db.getSlots());
        setMessages(prev => [...prev, agentMsg]);
        await db.saveChatMessage(userId, agentMsg);
      }
    });
    setTimeout(() => setAvatarState('idle'), 3000);
  };

  const handleSend = async () => {
    if (!inputText.trim()) return;
    const textToSend = inputText;
    const userMsg: Message = { id: Date.now().toString(), role: 'user', text: textToSend, timestamp: new Date() };
    setMessages(prev => [...prev, userMsg]);
    setInputText('');
    setIsCloudSyncing(true);
    await db.saveChatMessage(userId, userMsg);
    setIsCloudSyncing(false);
    await processMessageSend(textToSend);
  };

  const toggleTask = async (id: string) => {
    setTasks(tasks.map(t => t.id === id ? { ...t, isCompleted: !t.isCompleted } : t));
    await db.toggleTaskCompletion(userEmail, id);
  };

  const handleBookSlot = (slot: AppointmentSlot) => { setSelectedSlot(slot); setShowConsentModal(true); };

  const handleConsentSubmit = async (signature: string | File, mobile?: string) => {
    if (mobile) await handleProfileSave({ mobile });
    if (!selectedSlot) return;
    let signatureData = '';
    if (signature instanceof File) {
      const reader = new FileReader();
      reader.readAsDataURL(signature);
      reader.onload = async () => { signatureData = reader.result as string; await completeBooking(signatureData); };
    } else { signatureData = signature; await completeBooking(signatureData); }
  };

  const completeBooking = async (signatureData: string) => {
    if (!selectedSlot) return;
    const consent: Omit<ConsentData, 'counselorSignature' | 'counselorSignDate' | 'counselorId' | 'counselorName'> = {
      slotId: selectedSlot.id, studentId: userId, studentName,
      studentSignature: signatureData, studentSignDate: new Date().toISOString(),
    };
    await db.saveConsent(consent as ConsentData);
    setIsCloudSyncing(true);
    const success = await db.requestSlot(selectedSlot.id, userId, studentName);
    setIsCloudSyncing(false);
    if (success) { setSlots(await db.getSlots()); addNotification('Slot requested! Awaiting counselor approval.', 'success'); }
    else addNotification('Failed to request slot.', 'error');
    setShowConsentModal(false); setSelectedSlot(null);
  };

  const handleCancelSlot = async (slotId: string) => {
    addNotification('Slot booking cancelled', 'info');
    setIsCloudSyncing(true);
    await db.updateSlotStatus(slotId, 'open');
    setSlots(await db.getSlots());
    setIsCloudSyncing(false);
  };

  const handleProfileSave = async (updatedDetails: Partial<User>) => {
    await updateUser(user.id, updatedDetails);
    const updatedUser = await getUser(user.id);
    if (updatedUser) setUser(updatedUser);
    setShowEditProfileModal(false);
  };

  const handleP2PSend = async () => {
    if (!p2pInput.trim()) return;
    await db.sendP2PMessage({ id: Date.now().toString(), senderId: userId, receiverId: 'counselor_dimple', text: p2pInput, timestamp: new Date().toISOString(), isRead: false });
    setP2PInput('');
    setP2PMessages(await db.getP2PThread(userId, 'counselor_dimple'));
  };

  const openSlots = slots.filter(s => s.status === 'open');
  const generateChartData = (uid: string) => {
    const base = uid.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
    return [
      { name: 'Mon', stress: (base % 30) + 20 },
      { name: 'Tue', stress: (base % 40) + 40 },
      { name: 'Wed', stress: (base % 20) + 70 },
      { name: 'Thu', stress: ((base * 2) % 40) + 50 },
      { name: 'Fri', stress: ((base * 3) % 40) + 30 },
      { name: 'Sat', stress: ((base * 4) % 25) + 20 },
      { name: 'Sun', stress: (base % 15) + 15 },
    ];
  };
  const [chartData] = useState(() => generateChartData(userId));
  const notifColor = (type: string) =>
    type === 'success' ? 'bg-green-100 text-green-700 border-green-200' :
      type === 'error' ? 'bg-red-100 text-red-700 border-red-200' : 'bg-blue-100 text-blue-700 border-blue-200';

  return (
    <div className="min-h-screen flex flex-col bg-[#E6DDD0]">

      {/* ── Header ─────────────────────────────────────────────────────── */}
      <div className="w-full bg-[#DCD4C4] p-4 flex justify-between items-center shadow-md z-20">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-full bg-[#8A9A5B] flex items-center justify-center text-white font-bold text-xl">SU</div>
          <div>
            <h1 className="font-bold text-lg text-[#708090]">SpeakUp</h1>
            <p className="text-sm text-slate-500">Hi, {studentName}</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <button onClick={() => setShowP2P(true)} className="neu-icon-btn p-3 rounded-full text-[#708090]">
            <MessageSquare size={20} />
          </button>

          {/* Bell Dropdown */}
          <div className="relative" ref={bellRef}>
            <button onClick={() => { setShowBellDropdown(v => !v); if (!showBellDropdown) markAllRead(); }}
              className="neu-icon-btn p-3 rounded-full text-[#708090] relative">
              <Bell size={20} />
              {unreadCount > 0 && (
                <span className="absolute -top-1 -right-1 bg-red-500 text-white text-[10px] w-5 h-5 flex items-center justify-center rounded-full animate-bounce border-2 border-[#DCD4C4]">
                  {unreadCount > 9 ? '9+' : unreadCount}
                </span>
              )}
            </button>
            {showBellDropdown && (
              <div className="absolute right-0 mt-2 w-80 bg-white rounded-xl shadow-2xl border border-slate-200 z-50 overflow-hidden">
                <div className="px-4 py-3 border-b border-slate-100 flex justify-between items-center bg-gray-50">
                  <span className="font-bold text-slate-700 text-sm">Notifications</span>
                  <button onClick={clearAll} className="text-xs text-red-500 hover:text-red-700 flex items-center gap-1"><Trash2 size={12} /> Clear all</button>
                </div>
                <div className="max-h-72 overflow-y-auto">
                  {storedNotifications.length === 0 ? (
                    <p className="text-center text-slate-400 text-sm py-8">No notifications yet</p>
                  ) : storedNotifications.map(n => (
                    <div key={n.id} className={`flex items-start gap-3 px-4 py-3 border-b border-slate-50 last:border-0 ${notifColor(n.type)} border-l-4`}>
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium leading-snug">{n.message}</p>
                        <p className="text-[10px] opacity-60 mt-0.5">{new Date(n.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</p>
                      </div>
                      <button onClick={() => clearOne(n.id)} className="flex-shrink-0 opacity-40 hover:opacity-80 mt-0.5"><X size={14} /></button>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          <ProfileDropdown user={user} onEditProfile={() => setShowEditProfileModal(true)} onLogout={() => window.location.reload()} />
        </div>
      </div>

      <div className="flex flex-1 overflow-hidden">
        {/* Sidebar */}
        <div className="w-64 bg-[#DCD4C4] p-6 flex-col hidden md:flex">
          <div className="space-y-4">
            <button onClick={() => setActiveTab('home')} className={`w-full text-left px-4 py-3 rounded-lg transition-all flex items-center gap-3 ${activeTab === 'home' ? 'neu-pressed text-[#8A9A5B]' : 'text-slate-500 hover:bg-black/5'}`}><Home size={20} /> Home</button>
            <button onClick={() => setActiveTab('tasks')} className={`w-full text-left px-4 py-3 rounded-lg transition-all flex items-center gap-3 ${activeTab === 'tasks' ? 'neu-pressed text-[#8A9A5B]' : 'text-slate-500 hover:bg-black/5'}`}><CheckSquare size={20} /> Tasks</button>
            <button onClick={() => setActiveTab('booking')} className={`w-full text-left px-4 py-3 rounded-lg transition-all flex items-center gap-3 ${activeTab === 'booking' ? 'neu-pressed text-[#8A9A5B]' : 'text-slate-500 hover:bg-black/5'}`}><Calendar size={20} /> Slot Booking</button>
          </div>

          {/* Data Privacy Note */}
          <div className="mt-auto pt-6">
            <div className="p-3 bg-white/50 rounded-xl text-[10px] text-slate-400 leading-relaxed border border-slate-200">
              <p className="flex items-center gap-1 font-bold text-slate-500 mb-1"><Lock size={10} /> Privacy & Safety</p>
              <p>Data stays on this device. AI uses Google Gemini free API. Not used for ads or training. In a crisis: <strong className="text-red-500">iCall 9152987821</strong></p>
            </div>
          </div>
        </div>

        {/* API Error */}
        {apiError && (
          <div className="mx-4 mb-2 bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded-xl flex items-start gap-3 animate-in slide-in-from-top shadow-md">
            <Key size={20} className="mt-1 flex-shrink-0" />
            <div><h3 className="font-bold text-sm">Authentication Error</h3><p className="text-xs">The AI Token has expired or is invalid. Please update your <code>GEMINI_API_KEY</code>.</p></div>
          </div>
        )}

        {/* P2P Chat */}
        {showP2P && (
          <div className="absolute inset-0 z-40 bg-[#E6DDD0] flex flex-col animate-in slide-in-from-bottom duration-300">
            <div className="p-4 border-b border-gray-300 flex flex-col justify-center items-center bg-white/50 relative">
              <button onClick={() => setShowP2P(false)} className="absolute right-4 top-4 bg-white p-2 rounded-full shadow-sm hover:scale-105 transition-all"><XCircle className="text-slate-400 hover:text-red-500" size={24} /></button>
              <h3 className="font-black text-[#708090] text-lg">Chat with {selectedCounselor?.name ?? 'Counsellor'}</h3>
              <p className="text-xs text-slate-500 mb-3 font-medium">🛡️ End-to-End Encrypted</p>
              <button onClick={() => { setShowP2P(false); setShowCounselorPicker(true); }} className="px-4 py-2 bg-[#8A9A5B]/10 border border-[#8A9A5B]/30 shadow-sm rounded-xl text-sm text-[#8A9A5B] hover:bg-[#8A9A5B] hover:text-white transition-colors font-bold flex items-center gap-2">🔄 Switch Counsellor</button>
            </div>
            <div className="flex-1 overflow-y-auto p-4 space-y-3">
              {p2pMessages.map(m => (
                <div key={m.id} className={`flex ${m.senderId === userId ? 'justify-end' : 'justify-start'}`}>
                  <div className={`max-w-[80%] p-3 rounded-xl text-sm ${m.senderId === userId ? 'bg-[#8A9A5B] text-white' : 'bg-white text-slate-600'}`}>{m.text}</div>
                </div>
              ))}
              {p2pMessages.length === 0 && <p className="text-center text-slate-400 text-xs mt-10">Start a secure conversation with your counselor.</p>}
            </div>
            <div className="p-4 bg-white/50">
              <div className="flex gap-2">
                <input type="text" value={p2pInput} onChange={e => setP2PInput(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && handleP2PSend()} placeholder="Type a message..." className="flex-1 p-2 rounded-lg border border-gray-300 outline-none" />
                <button onClick={handleP2PSend} className="bg-[#8A9A5B] text-white p-2 rounded-lg"><Send size={18} /></button>
              </div>
            </div>
          </div>
        )}

        {/* ── Main Content ───────────────────────────────────────────────── */}
        <div className="flex-1 p-6 overflow-hidden flex flex-col pb-20 md:pb-6">

          {/* ── HOME TAB ─────────────────────────────────────────────────── */}
          {activeTab === 'home' && (
            <div className="w-full h-full flex flex-col gap-4 overflow-y-auto pr-2 scrollbar-hide">
              {/* Top Row: Environment Widget */}
              <div className="flex-shrink-0">
                <EnvironmentWidget variant="student" />
              </div>

              {/* Middle Row: Wellness Wall (Ribbon View) */}
              <div className="flex-shrink-0">
                <div className="flex items-center gap-2 mb-3">
                  <Newspaper size={18} className="text-[#8A9A5B]" />
                  <h3 className="font-bold text-[#708090] text-lg">Wellness Wall</h3>
                  <span className="text-xs bg-[#8A9A5B]/10 text-[#8A9A5B] px-2 py-0.5 rounded-full">From the Counselling Cell</span>
                </div>
                {posts.length === 0 ? (
                  <div className="bg-white/60 rounded-2xl p-6 text-center text-slate-400">
                    <Newspaper size={24} className="mx-auto mb-2 opacity-30" />
                    <p className="text-sm">No posts yet. Check back soon!</p>
                  </div>
                ) : (
                  <div className="flex gap-4 overflow-x-auto pb-2 scrollbar-hide snap-x">
                    {posts.map((post, idx) => (
                      <div key={post.id} className={`snap-start flex-shrink-0 ${idx === 0 ? 'w-[75%] md:w-[60%]' : 'w-[45%] md:w-[35%]'}`}>
                        <WallPostCard post={post} />
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Open Slots Strip */}
              {slots.filter(s => s.status === 'open').length > 0 && (
                <div className="flex-shrink-0 bg-white/40 p-4 rounded-3xl border border-white/50">
                  <div className="flex justify-between items-center mb-3">
                    <h3 className="font-bold text-[#708090] flex items-center gap-2"><Calendar size={16} /> Available Counselling Slots</h3>
                    <button onClick={() => setActiveTab('booking')} className="text-[#8A9A5B] text-xs font-bold hover:underline">Book Now</button>
                  </div>
                  <div className="flex gap-3 overflow-x-auto scrollbar-hide pb-1">
                    {slots.filter(s => s.status === 'open').slice(0, 3).map(slot => (
                      <div key={slot.id} className="flex-shrink-0 bg-white p-3 rounded-2xl shadow-sm border border-slate-100 min-w-[140px]">
                        <p className="text-xs text-slate-400 font-bold uppercase">{slot.date}</p>
                        <p className="font-bold text-[#708090]">{slot.time}</p>
                        <p className="text-[10px] text-slate-500 truncate">{COUNSELORS.find(c => c.id === slot.counselorId)?.name || 'Counsellor'}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Bottom Row: Tasks (Left) + Workload Meter (Right) */}
              <div className="flex-1 grid grid-cols-1 md:grid-cols-2 gap-4 min-h-0">
                {/* Tasks Column */}
                <div className="bg-white/40 rounded-3xl p-4 flex flex-col border border-white/50 overflow-hidden">
                  <div className="flex justify-between items-center mb-3 flex-shrink-0">
                    <h3 className="font-bold text-[#708090] flex items-center gap-2">
                      <CheckSquare size={16} /> Wellness Quests
                    </h3>
                    <button onClick={() => setActiveTab('tasks')} className="text-[#8A9A5B] text-xs font-bold hover:underline">View All</button>
                  </div>
                  <div className="flex-1 overflow-y-auto space-y-2 pr-1 scrollbar-hide">
                    {/* Inline Quick Quest entry points */}
                    <button onClick={() => setOdyssey({ open: true, type: 'GAD7' })} className="w-full text-left p-3 rounded-xl bg-indigo-50 border border-indigo-100 hover:border-indigo-300 transition-colors flex items-center justify-between group">
                      <div>
                        <p className="text-sm font-bold text-indigo-900">The Anxiety Realm 🌀</p>
                        <p className="text-[10px] text-indigo-500">GAD-7 Survey</p>
                      </div>
                      <ChevronRight size={14} className="text-indigo-300 group-hover:text-indigo-500" />
                    </button>
                    {tasks.filter(t => t.assignedBy !== 'system').slice(0, 3).map(task => (
                      <div key={task.id} className={`p-3 rounded-xl flex items-center gap-3 ${task.isCompleted ? 'bg-white/50 opacity-60' : 'bg-white shadow-sm'}`}>
                        <div className={`w-4 h-4 rounded border flex items-center justify-center flex-shrink-0 ${task.isCompleted ? 'border-[#8A9A5B] bg-[#8A9A5B]' : 'border-slate-300'}`}>
                          {task.isCompleted && <CheckSquare size={10} className="text-white" />}
                        </div>
                        <span className={`text-sm truncate ${task.isCompleted ? 'text-slate-400 line-through' : 'text-slate-700'}`}>{task.title}</span>
                      </div>
                    ))}
                    {tasks.filter(t => t.assignedBy !== 'system').length === 0 && (
                      <p className="text-center text-xs text-slate-400 py-2">No active tasks</p>
                    )}
                  </div>
                </div>

                {/* Workload Meter Column */}
                <div className="neu-pressed rounded-3xl p-4 flex flex-col overflow-hidden">
                  <div className="flex justify-between items-center mb-2 flex-shrink-0">
                    <h3 className="font-bold text-[#708090] flex items-center gap-2"><Activity size={16} /> Workload Meter</h3>
                    <span className="text-[10px] bg-[#CC5500]/10 text-[#CC5500] px-2 py-0.5 rounded-full">Peak Load</span>
                  </div>
                  <div className="flex-1 min-h-[120px]">
                    <ResponsiveContainer width="100%" height="100%">
                      <AreaChart data={chartData} margin={{ top: 5, right: 0, left: 0, bottom: 0 }}>
                        <Tooltip />
                        <Area type="monotone" dataKey="stress" stroke="#CC5500" fillOpacity={0.2} fill="#CC5500" />
                      </AreaChart>
                    </ResponsiveContainer>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* ── TASKS TAB ─────────────────────────────────────────────────── */}
          {activeTab === 'tasks' && (
            <div className="animate-in slide-in-from-bottom-10 duration-500 space-y-6">
              <h2 className="text-2xl font-bold text-[#708090]">Wellness Routines</h2>

              {/* ── Standard Quests (GAD-7 + BDI) — shown to all students ── */}
              <div>
                <div className="flex items-center gap-2 mb-3">
                  <Sword size={16} className="text-emerald-600" />
                  <h3 className="font-bold text-slate-600 text-base">Standard Quests</h3>
                  <span className="text-[10px] bg-emerald-100 text-emerald-700 px-2 py-0.5 rounded-full font-bold">Wellness Odyssey</span>
                </div>
                <div className="grid grid-cols-1 gap-4">
                  {/* GAD-7 Quest */}
                  <div className="bg-gradient-to-br from-indigo-900 via-slate-800 to-indigo-900 rounded-2xl p-5 border border-indigo-700/40 shadow-lg">
                    <div className="flex items-start justify-between">
                      <div>
                        <div className="text-2xl mb-1">🌀</div>
                        <h4 className="font-black text-white text-base">The Anxiety Realm</h4>
                        <p className="text-indigo-300 text-xs">GAD-7 · 7 Guardians · Up to 140 XP</p>
                        <p className="text-slate-400 text-xs mt-1">A brief survey measuring generalized anxiety symptoms.</p>
                      </div>
                      <button onClick={() => setOdyssey({ open: true, type: 'GAD7' })}
                        className="bg-emerald-500 hover:bg-emerald-400 text-black font-bold px-4 py-2 rounded-xl text-sm shadow-lg shadow-emerald-500/30 transition-all hover:scale-105 flex items-center gap-1.5">
                        <Map size={14} /> Begin
                      </button>
                    </div>
                  </div>

                  {/* BDI Quest */}
                  <div className="bg-gradient-to-br from-purple-900 via-slate-800 to-purple-900 rounded-2xl p-5 border border-purple-700/40 shadow-lg">
                    <div className="flex items-start justify-between">
                      <div>
                        <div className="text-2xl mb-1">🌑</div>
                        <h4 className="font-black text-white text-base">The Depression Depths</h4>
                        <p className="text-purple-300 text-xs">BDI-II · 21 Guardians · Up to 420 XP</p>
                        <p className="text-slate-400 text-xs mt-1">Beck's Depression Inventory — an evidence-based wellness check-in.</p>
                      </div>
                      <button onClick={() => setOdyssey({ open: true, type: 'BDI' })}
                        className="bg-emerald-500 hover:bg-emerald-400 text-black font-bold px-4 py-2 rounded-xl text-sm shadow-lg shadow-emerald-500/30 transition-all hover:scale-105 flex items-center gap-1.5">
                        <Map size={14} /> Begin
                      </button>
                    </div>
                  </div>
                </div>
              </div>

              {/* ── Counsellor-Assigned Tasks ── */}
              <div>
                <h3 className="font-bold text-slate-600 text-base mb-3">Assigned by Counsellor</h3>
                {tasks.filter(t => t.assignedBy !== 'system').length === 0 && (
                  <p className="text-center text-slate-400 text-sm py-4">No tasks assigned yet by your counsellor.</p>
                )}
                <div className="space-y-4">
                  {tasks.filter(t => t.assignedBy !== 'system').map(task => (
                    <div key={task.id} onClick={() => toggleTask(task.id)} className={`p-4 rounded-2xl flex items-center gap-4 transition-all cursor-pointer ${task.isCompleted ? 'neu-pressed opacity-60' : 'neu-flat'}`}>
                      <div className={`w-6 h-6 rounded-full border-2 flex items-center justify-center flex-shrink-0 ${task.isCompleted ? 'border-[#8A9A5B] bg-[#8A9A5B]' : 'border-slate-400'}`}>
                        {task.isCompleted && <CheckSquare size={14} className="text-white" />}
                      </div>
                      <div>
                        <h4 className={`font-bold ${task.isCompleted ? 'text-slate-400 line-through' : 'text-[#708090]'}`}>{task.title}</h4>
                        <p className="text-xs text-slate-400">Assigned by {task.assignedBy}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* Consent Modal */}
          {showConsentModal && selectedSlot && (
            <ConsentForm role="student" studentName={studentName} program="PGDM"
              onClose={() => setShowConsentModal(false)} onSubmit={handleConsentSubmit} user={user} />
          )}
          {showEditProfileModal && (
            <EditProfileModal user={user} onClose={() => setShowEditProfileModal(false)} onSave={handleProfileSave} />
          )}

          {/* ── BOOKING TAB ───────────────────────────────────────────────── */}
          {activeTab === 'booking' && (
            <div className="animate-in slide-in-from-right-10 duration-500 space-y-4">
              <h3 className="text-xl font-bold text-[#708090] mb-6">Book a Sanctuary Slot</h3>
              {slots.map(slot => {
                const isMyBooking = slot.bookedByStudentId === userId;
                let btnText = 'Select', btnClass = 'bg-[#E6DDD0] text-[#8A9A5B] border border-[#8A9A5B]', statusText = '';
                if (slot.status === 'confirmed') { btnText = isMyBooking ? 'Confirmed' : 'Taken'; btnClass = isMyBooking ? 'bg-green-600 text-white' : 'bg-gray-200 text-gray-400'; statusText = isMyBooking ? 'Slot Confirmed' : ''; }
                else if (slot.status === 'requested') { btnText = isMyBooking ? 'Cancel Req' : 'Pending'; btnClass = isMyBooking ? 'bg-yellow-500 text-white' : 'bg-gray-200 text-gray-400'; statusText = isMyBooking ? 'Waiting Approval' : ''; }
                return (
                  <div key={slot.id} className="neu-flat p-4 rounded-2xl flex justify-between items-center">
                    <div>
                      <div className="font-bold text-[#708090]">{slot.counselorName}</div>
                      <div className="text-sm text-slate-400">{slot.date} • {slot.time}</div>
                      {statusText && <div className="text-[10px] uppercase font-bold text-slate-500 mt-1">{statusText}</div>}
                    </div>
                    <div className="flex items-center gap-2">
                      {isMyBooking && slot.status === 'confirmed' && (
                        <button onClick={() => downloadConsentAsPDF(slot.id)} className="p-2 rounded-full bg-gray-200 text-gray-600 hover:bg-gray-300"><Download size={16} /></button>
                      )}
                      <button disabled={slot.status !== 'open' && !isMyBooking}
                        onClick={() => { if (slot.status === 'open') handleBookSlot(slot); if (isMyBooking && slot.status === 'requested') handleCancelSlot(slot.id); }}
                        className={`px-4 py-2 rounded-xl text-sm font-bold shadow-sm transition-all active:scale-95 ${btnClass}`}>{btnText}</button>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>

      {/* ── Medical Disclaimer Strip ─────────────────────────────────────── */}
      <div className="bg-amber-50 border-t border-amber-200 px-4 py-2 text-[10px] text-amber-700 text-center hidden md:block">
        <ShieldAlert size={11} className="inline mr-1" />
        <strong>Wellness Tool Only:</strong> SParsh is not a doctor or clinical tool. For urgent help: <strong>iCall 9152987821</strong> (Mon–Sat 8am–10pm) • <strong>Vandrevala Foundation: 1860-2662-345</strong> (24/7)
      </div>

      {/* ── Floating Chat Button ──────────────────────────────────────────── */}
      <div className="fixed bottom-8 right-8 z-30">
        <button onClick={() => setShowCounselorPicker(true)} className="w-16 h-16 rounded-full bg-[#8A9A5B] flex items-center justify-center shadow-lg text-white animate-pulse">
          <Heart size={32} fill="white" />
        </button>
      </div>

      {/* ── Chat Window ───────────────────────────────────────────────────── */}
      {isChatOpen && (
        <div className="fixed bottom-28 right-8 w-96 h-[62vh] bg-white/90 backdrop-blur-md rounded-2xl shadow-2xl flex flex-col z-30 animate-in slide-in-from-bottom-10 duration-500 border border-slate-200">
          <div className="p-3 border-b flex justify-between items-center bg-[#8A9A5B]/10 rounded-t-2xl">
            <div className="flex items-center gap-2">
              <span className="font-bold text-[#708090]">SParsh AI</span>
              <span className="flex items-center gap-1 text-[10px] text-slate-400 bg-white/70 px-2 py-0.5 rounded-full border border-slate-200">
                <Lock size={9} /> Free API · Locally Encrypted
              </span>
            </div>
            <button onClick={() => setIsChatOpen(false)} className="text-slate-400 hover:text-slate-600"><XCircle size={18} /></button>
          </div>

          {/* Privacy notice banner */}
          <div className="px-4 py-2 bg-amber-50 border-b border-amber-100 text-[10px] text-amber-700 flex items-start gap-2">
            <ShieldAlert size={12} className="mt-0.5 flex-shrink-0" />
            <span>SParsh is a <strong>wellness companion</strong>, not a medical professional. For clinical support, please see a doctor.</span>
          </div>

          <div className="flex-1 overflow-y-auto p-4 space-y-4 scrollbar-hide">
            {messages.map(msg => (
              <div key={msg.id} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                <div className={`max-w-[85%] p-3 rounded-xl text-sm ${msg.role === 'user' ? 'bg-[#8A9A5B] text-white' : 'bg-gray-100 text-slate-700'}`}>
                  {msg.text}
                  {/* Inline slot booking cards */}
                  {msg.role !== 'user' && msg.metadata?.type === 'booking_suggestion' && openSlots.length > 0 && (
                    <div className="mt-3 space-y-2">
                      <p className="text-xs font-bold text-slate-500 uppercase tracking-wide">Available Slots</p>
                      {openSlots.slice(0, 3).map(slot => (
                        <div key={slot.id} className="bg-white rounded-lg p-2.5 border border-[#8A9A5B]/30 flex justify-between items-center gap-2 shadow-sm">
                          <div>
                            <p className="text-xs font-bold text-[#708090]">{slot.counselorName}</p>
                            <p className="text-[11px] text-slate-400">{slot.date} · {slot.time}</p>
                          </div>
                          <button onClick={() => { handleBookSlot(slot); setIsChatOpen(false); }}
                            className="text-xs bg-[#8A9A5B] text-white px-3 py-1.5 rounded-lg font-bold hover:bg-[#76854d] transition-colors flex-shrink-0">
                            Book Now
                          </button>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            ))}
            {isLoading && <div className="text-center text-xs text-slate-400 animate-pulse">SParsh is listening...</div>}
            <div ref={messagesEndRef} />
          </div>

          <div className="p-4 border-t border-slate-100 flex flex-col gap-3">
            {/* Predefined prompts */}
            <div className="flex gap-2 overflow-x-auto scrollbar-hide pb-1">
              {["How to book a slot?", "Is my privacy secure?", "Feeling stressed"].map(prompt => (
                <button key={prompt} onClick={() => { setInputText(prompt); processMessageSend(prompt); }}
                  className="whitespace-nowrap bg-gray-100 hover:bg-gray-200 text-slate-600 text-[11px] px-3 py-1.5 rounded-full border border-gray-200 transition-colors">
                  {prompt}
                </button>
              ))}
            </div>
            <div className="flex gap-2">
              <input type="text" value={inputText} onChange={(e) => setInputText(e.target.value)}
                onKeyDown={(e) => { if (e.key === 'Enter' && inputText.trim()) { handleSend(); } }} placeholder="Speak to SParsh..."
                className="flex-1 p-2 rounded-lg border border-gray-200 outline-none text-sm" />
              <button disabled={!inputText.trim()} onClick={handleSend} className="bg-[#8A9A5B] disabled:bg-[#8A9A5B]/50 text-white p-2 rounded-lg transition-colors"><Send size={18} /></button>
            </div>
          </div>
        </div>
      )}

      {/* Mobile Bottom Nav */}
      <div className="md:hidden fixed bottom-0 left-0 w-full bg-[#DCD4C4] border-t border-gray-300 p-2 flex justify-around items-center z-20">
        <button onClick={() => setActiveTab('home')} className={`p-2 rounded-full ${activeTab === 'home' ? 'text-[#8A9A5B]' : 'text-slate-500'}`}><Home size={24} /></button>
        <button onClick={() => setActiveTab('tasks')} className={`p-2 rounded-full ${activeTab === 'tasks' ? 'text-[#8A9A5B]' : 'text-slate-500'}`}><CheckSquare size={24} /></button>
        <button onClick={() => setActiveTab('booking')} className={`p-2 rounded-full ${activeTab === 'booking' ? 'text-[#8A9A5B]' : 'text-slate-500'}`}><Calendar size={24} /></button>
      </div>

      {/* ── Counselor Picker Modal ──────────────────────────────────────── */}
      {showCounselorPicker && (
        <div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center p-6 backdrop-blur-sm">
          <div className="bg-white rounded-3xl shadow-2xl p-6 w-full max-w-sm animate-in zoom-in-95 duration-300">
            <h3 className="text-lg font-bold text-[#708090] mb-1">Who would you like to talk to?</h3>
            <p className="text-xs text-slate-400 mb-5">Your conversations are secure and private 🔒</p>
            <div className="space-y-3">
              <button onClick={() => { setShowCounselorPicker(false); setIsChatOpen(true); }}
                className="w-full flex items-center gap-4 p-4 rounded-2xl border border-indigo-100 bg-indigo-50/50 hover:border-indigo-300 hover:bg-indigo-50 transition-all text-left">
                <div className="w-12 h-12 rounded-full bg-indigo-500 flex items-center justify-center text-white font-bold flex-shrink-0"><Sparkles size={20} /></div>
                <div>
                  <p className="font-bold text-indigo-900">SParsh AI</p>
                  <p className="text-xs text-indigo-500">24/7 Wellness Companion</p>
                </div>
              </button>
              {COUNSELORS.map(c => (
                <button key={c.id} onClick={async () => {
                  setSelectedCounselor(c);
                  setShowCounselorPicker(false);
                  setShowP2P(true);
                  setP2PMessages(await db.getP2PThread(userId, c.id));
                }}
                  className="w-full flex items-center gap-4 p-4 rounded-2xl border border-slate-200 hover:border-[#8A9A5B] hover:bg-[#8A9A5B]/5 transition-all text-left">
                  <div className="w-12 h-12 rounded-full bg-[#8A9A5B] flex items-center justify-center text-white font-bold flex-shrink-0">{c.avatar}</div>
                  <div>
                    <p className="font-bold text-slate-700">{c.name}</p>
                    <p className="text-xs text-slate-400">{c.specialization}</p>
                  </div>
                </button>
              ))}
            </div>
            <button onClick={() => setShowCounselorPicker(false)} className="mt-4 w-full text-center text-sm text-slate-400 hover:text-slate-600">Cancel</button>
          </div>
        </div>
      )}

      {/* ── Wellness Odyssey Overlay ──────────────────────────────────────── */}
      {odyssey.open && (
        <WellnessOdyssey
          surveyType={odyssey.type}
          userId={userId}
          onClose={() => setOdyssey(prev => ({ ...prev, open: false }))}
        />
      )}

      {/* ── Onboarding Tour ─────────────────────────────────────────────────── */}
      {showOnboarding && (
        <OnboardingTour
          onComplete={() => {
            localStorage.setItem(`speakup_onboarding_${userId}`, 'true');
            setShowOnboarding(false);
          }}
        />
      )}
    </div>
  );
};

export default StudentDashboard;