import React, { useState, useEffect, useRef } from 'react';
import { Pin, Send, XCircle, Home, CheckSquare, Calendar, Lock, Key, Activity, Newspaper, ChevronDown, ChevronUp, Bell, Heart, Upload, LogOut, Sun, CloudRain, Wind, AlertCircle, Trash2, Edit2, Plus, Sword, Map, Settings, ShieldAlert, Sparkles, ChevronRight, MessageSquare, X, Download } from 'lucide-react';
import { AreaChart, Area, Tooltip, ResponsiveContainer } from 'recharts';
import ProfileDropdown from './ProfileDropdown';
import ProfileSettingsModal from './ProfileSettingsModal';
import EnvironmentWidget from './EnvironmentWidget';
import WellnessOdyssey from './WellnessOdyssey';
import { sendMessageToSParsh } from '../services/geminiService';
import { analyzeSentimentAndSchedule } from '../services/sentimentAgent';
import { Message, WellnessTask, AppointmentSlot, P2PMessage, ConsentData, User, WellnessPost } from '../types';
import ConsentForm from './ConsentForm';
import * as db from '../services/storage';
import { useSParsh } from '../contexts/SParshContext';
import { useNotification } from '../contexts/NotificationContext';
import OnboardingTour from './OnboardingTour';
import { getUser, updateUser, clearSParshHistory } from '../services/storage';
import { useStorageSync } from '../hooks/useStorageSync';
import { COUNSELORS } from '../constants';
import { getForgedGames, GameMetadata } from '../services/ragService';
import { detectCrisisInText } from '../services/aiService';
import { getSlots, requestSlot as firestoreRequestSlot, updateSlotStatus as firestoreUpdateSlotStatus, subscribeToSlots } from '../services/slotService';

interface Props {
  triggerCrisis: () => void;
  userEmail: string;
  userId: string;
  user: User;
  onLogout?: () => void;
}

/** Generate a PDF for a confirmed consent */
const downloadConsentAsPDF = async (slotId: string) => {
  const consent = await db.getConsentForSlot(slotId);
  if (!consent) return;
  const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"/><title>Consent – ${consent.studentName}</title>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet"/>
  <style>@page{margin:24mm 20mm;}body{font-family:'Inter',sans-serif;font-size:13px;color:#222;line-height:1.7;}
  h1{font-size:18px;text-align:center;}.info{background:#f7f7f7;padding:12px;border-radius:6px;margin:12px 0;display:grid;grid-template-columns:1fr 1fr;gap:6px;border:1px solid #e0e0e0;}
  .sigs{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:20px;border-top:2px solid #e0e0e0;padding-top:16px;}
  .sig-box{border:1px solid #ccc;border-radius:6px;padding:12px;min-height:80px;}.footer{text-align:center;color:#aaa;font-size:10px;margin-top:24px;}
  </style></head><body>
  <h1>Informed Consent for Psychological Counseling</h1>
  <div class="info">
    <div><strong>Student:</strong> ${consent.studentName}</div>
    <div><strong>Counselor:</strong> ${consent.counselorName || 'Ms. Dimple Wagle'}</div>
    <div><strong>Slot ID:</strong> ${consent.slotId}</div>
    <div><strong>Date:</strong> ${new Date(consent.studentSignDate).toLocaleString()}</div>
  </div>
  <p>This consent confirms voluntary participation in psychological counselling at SPJIMR under the assigned counselor, subject to standard confidentiality protocols.</p>
  <div class="sigs">
    <div class="sig-box"><strong>Student Signature</strong><br/>${consent.studentSignature?.startsWith('data:image')
      ? `<img src="${consent.studentSignature}" style="max-height:60px;margin-top:4px;"/>`
      : `<p style="font-family:cursive;font-size:22px;">${consent.studentSignature || '—'}</p>`
    }<p style="font-size:11px;color:#666;">Date: ${new Date(consent.studentSignDate).toLocaleString()}</p></div>
    <div class="sig-box"><strong>Counselor Signature</strong><br/>
    <p style="font-family:cursive;font-size:22px;">${consent.counselorSignature || 'Pending'}</p>
    <p style="font-size:11px;color:#666;">Date: ${consent.counselorSignDate ? new Date(consent.counselorSignDate).toLocaleString() : 'Pending'}</p></div>
  </div>
  <p class="footer">Generated by SPeakUp | SPJIMR Mental Health Ecosystem</p>
  <script>window.onload=()=>window.print();</script>
  </body></html>`;
  const win = window.open('', '_blank');
  if (win) { win.document.write(html); win.document.close(); }
};

const WallPostCard: React.FC<{ post: WellnessPost }> = ({ post }) => {
  const [expanded, setExpanded] = useState(false);
  const lines = post.body.split('\n');
  const isLong = lines.length > 5 || post.body.length > 400;
  const preview = isLong ? post.body.slice(0, 380) + '…' : post.body;

  return (
    <>
      <div className={`rounded-2xl p-5 shadow-sm border cursor-pointer hover:shadow-md ${post.isPinned ? 'bg-amber-50 border-amber-200' : 'bg-white border-slate-100'} transition-all h-full flex flex-col`} onClick={() => isLong && setExpanded(true)}>
        {post.isPinned && (
          <div className="flex items-center gap-1 text-amber-600 text-[11px] font-bold uppercase tracking-wider mb-2">
            <Pin size={11} /> Pinned
          </div>
        )}
        <h3 className="font-bold text-[#708090] text-base mb-1 leading-snug">{post.title}</h3>
        <p className="text-[11px] text-slate-400 mb-3">
          📝 {post.authorName} · {new Date(post.postedAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}
        </p>
        <div className="text-sm text-slate-600 leading-relaxed whitespace-pre-wrap flex-1">{preview}</div>
        {isLong && (
          <div className="mt-3 flex items-center gap-1 text-[#8A9A5B] text-xs font-bold">
            Read full post <ChevronRight size={13} />
          </div>
        )}
      </div>

      {expanded && (
        <div className="fixed inset-0 z-[100] bg-black/60 backdrop-blur-sm flex items-center justify-center p-4 sm:p-6 animate-in fade-in duration-200" onClick={() => setExpanded(false)}>
          <div className="w-full max-w-2xl bg-white rounded-3xl shadow-2xl overflow-hidden flex flex-col max-h-[85vh] animate-in zoom-in-95 duration-300" onClick={e => e.stopPropagation()}>
            <div className={`p-6 border-b flex justify-between items-start ${post.isPinned ? 'bg-amber-50 border-amber-100' : 'bg-slate-50 border-slate-100'}`}>
              <div>
                {post.isPinned && <div className="flex items-center gap-1 text-amber-600 text-xs font-bold uppercase tracking-wider mb-2"><Pin size={12} /> Pinned Announcement</div>}
                <h2 className="text-xl font-black text-[#708090] leading-snug">{post.title}</h2>
                <p className="text-xs text-slate-500 mt-2">Posted by <strong>{post.authorName}</strong> on {new Date(post.postedAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
              </div>
              <button onClick={() => setExpanded(false)} className="p-2 bg-white rounded-full shadow-sm text-slate-400 hover:text-red-500 hover:scale-105 transition-all">
                <X size={20} />
              </button>
            </div>
            <div className="p-6 overflow-y-auto text-slate-700 leading-relaxed whitespace-pre-wrap text-sm md:text-base scrollbar-hide">
              {post.body}
            </div>
          </div>
        </div>
      )}
    </>
  );
};

// ─── Main Dashboard ────────────────────────────────────────────────────────
const StudentDashboard: React.FC<Props> = ({ triggerCrisis, userEmail, userId, user: initialUser, onLogout }) => {
  const { addNotification, storedNotifications, unreadCount, markAllRead, clearAll, clearOne } = useNotification();
  const [user, setUser] = useState<User>(initialUser);
  const [showProfileSettings, setShowProfileSettings] = useState(false);
  const { setVibe, setAvatarState } = useSParsh();

  const studentName = (() => {
    const namePart = userEmail.split('.')[1]?.split('@')[0];
    if (!namePart) return 'Student';
    return namePart.charAt(0).toUpperCase() + namePart.slice(1);
  })();

  const [activeTab, setActiveTab] = useState<'home' | 'tasks' | 'booking'>('home');
  const [isChatOpen, setIsChatOpen] = useState(false);
  const [messages, setMessages] = useState<Message[]>([]);
  const [inputText, setInputText] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isCloudSyncing, setIsCloudSyncing] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const [apiError, setApiError] = useState(false);
  const [showBellDropdown, setShowBellDropdown] = useState(false);
  const bellRef = useRef<HTMLDivElement>(null);

  const [tasks, setTasks] = useState<WellnessTask[]>([]);
  const [slots, setSlots] = useState<AppointmentSlot[]>([]);
  const [showConsentModal, setShowConsentModal] = useState(false);
  const [selectedSlot, setSelectedSlot] = useState<AppointmentSlot | null>(null);

  const [showP2P, setShowP2P] = useState(false);
  const [p2pMessages, setP2PMessages] = useState<P2PMessage[]>([]);
  const [p2pInput, setP2PInput] = useState('');
  const [unreadP2P, setUnreadP2P] = useState(0);

  // Wall feed posts
  const [posts, setPosts] = useState<WellnessPost[]>([]);

  // Wellness Odyssey overlay
  const [odyssey, setOdyssey] = useState<{ open: boolean; type: 'GAD7' | 'BDI' | string }>({ open: false, type: 'GAD7' });
  const [forgedGames, setForgedGames] = useState<Record<string, GameMetadata>>({});

  // Two-counselor selector
  const [selectedCounselor, setSelectedCounselor] = useState<typeof COUNSELORS[0] | null>(null);
  const [showCounselorPicker, setShowCounselorPicker] = useState(false);

  // Onboarding
  const [showOnboarding, setShowOnboarding] = useState(false);

  // In-chat slot picker (Feature 3)
  const [showChatSlotPicker, setShowChatSlotPicker] = useState(false);

  // How It Works overlay (Feature 6)
  const [showHowItWorks, setShowHowItWorks] = useState(false);
  const [howItWorksSection, setHowItWorksSection] = useState<number | null>(null);

  // Follow-up nudge (Feature 5)
  const [showFollowUpNudge, setShowFollowUpNudge] = useState(false);
  const [followUpDays, setFollowUpDays] = useState(0);

  // ── Clear SParsh history on logout or tab close ───────────────────────────
  useEffect(() => {
    const handleUnload = () => clearSParshHistory(userId);
    window.addEventListener('beforeunload', handleUnload);
    return () => window.removeEventListener('beforeunload', handleUnload);
  }, [userId]);

  // Close bell dropdown on outside click
  // ── Real-time cross-tab sync (zero-latency, fires on every localStorage change in other tabs)
  useStorageSync(async (changedKey) => {
    // Slots are now on Firestore — no localStorage sync needed for slots
    if (changedKey.startsWith('speakup_cloud_tasks')) {
      setTasks(await db.getTasks(userEmail));
    }
    if (changedKey.startsWith('speakup_cloud_posts')) {
      setPosts(await db.getAllPosts());
    }
    if (changedKey.startsWith('speakup_cloud_p2p')) {
      if (showP2P && selectedCounselor) {
        setP2PMessages(await db.getP2PThread(userId, selectedCounselor.id));
        await db.markThreadAsRead(userId, selectedCounselor.id);
        setUnreadP2P(0);
      } else {
        setUnreadP2P(await db.getUnreadP2PCount(userId));
      }
    }
  });

  // ── Polling interval (fallback for same-tab updates and Safari)
  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (bellRef.current && !bellRef.current.contains(e.target as Node)) setShowBellDropdown(false);
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, []);

  // ── Load data on mount + 5-second polling (catches same-tab updates)
  useEffect(() => {
    const hasSeenOnboarding = localStorage.getItem(`speakup_onboarding_${userId}`);
    if (!hasSeenOnboarding) setShowOnboarding(true);

    const loadData = async () => {
      setIsCloudSyncing(true);
      const [history, tasksData, postsData, initialUnread, forgedData] = await Promise.all([
        db.getChatHistory(userId),
        db.getTasks(userEmail),
        db.getAllPosts(),
        db.getUnreadP2PCount(userId),
        getForgedGames()
      ]);
      setMessages(history);
      setTasks(tasksData);
      setPosts(postsData);
      setForgedGames(forgedData || {});

      // Follow-up nudge: only for students who have a prior confirmed booking
      const dismissedUntil = localStorage.getItem(`speakup_nudge_dismissed_${userId}`);
      const isDismissed = dismissedUntil && new Date(dismissedUntil) > new Date();
      if (!isDismissed) {
        /* Since slots are now loaded asynchronously via subscribeToSlots, 
           we handle the nudge effect separately where slots are updated */
      }

      setUnreadP2P(initialUnread);
      setIsCloudSyncing(false);
    };
    loadData();

    // Polling for P2P and posts (slots handled by Firestore subscribeToSlots)
    const interval = setInterval(async () => {
      setPosts(await db.getAllPosts());
      if (showP2P) {
        await db.markThreadAsRead(userId, 'counselor_dimple');
        setUnreadP2P(0);
        setP2PMessages(await db.getP2PThread(userId, 'counselor_dimple'));
      } else {
        setUnreadP2P(await db.getUnreadP2PCount(userId));
      }
    }, 5000);
    return () => clearInterval(interval);
  }, [userId, userEmail, showP2P]);

  // ── Real-time Firestore slot subscription (instant cross-device updates)
  useEffect(() => {
    const unsub = subscribeToSlots((updatedSlots) => {
      setSlots(updatedSlots);
    });
    return () => unsub();
  }, []);

  const scrollToBottom = () => messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  useEffect(() => scrollToBottom(), [messages]);

  const handleCrisis = async () => {
    triggerCrisis();
    await db.sendP2PMessage({
      id: Date.now().toString(),
      senderId: 'system',
      receiverId: 'counselor_dimple_wagle',
      text: `🚨 EMERGENCY ALERT: ${studentName} (${userEmail}) triggered the SParsh Crisis Protocol. Immediate attention required.`,
      timestamp: new Date().toISOString(),
      isRead: false
    });
  };

  const processMessageSend = async (textToSend: string) => {
    setAvatarState('listening');
    setIsLoading(true);
    setApiError(false);

    const validHistory = messages.filter(m => !m.text.includes('Token Limit Reached'));
    const history = validHistory.map(m => ({ role: m.role === 'agent' ? 'model' : m.role, parts: [{ text: m.text }] }));

    const response = await sendMessageToSParsh(history, textToSend);

    setIsLoading(false);
    setAvatarState('speaking');

    if (response.text.includes('API key not valid') || response.text.includes('System Error')) setApiError(true);
    if (response.detectedMood) setVibe(response.detectedMood);
    if (response.isCrisis) await handleCrisis();

    const modelMsg: Message = { id: (Date.now() + 1).toString(), role: 'model', text: response.text, timestamp: new Date() };
    const updatedMessages = [
      ...validHistory,
      { id: Date.now().toString(), role: 'user', text: textToSend, timestamp: new Date() } as Message,
      modelMsg,
    ];
    setMessages(updatedMessages);
    setIsCloudSyncing(true);
    await db.saveChatMessage(userId, modelMsg);
    setIsCloudSyncing(false);

    analyzeSentimentAndSchedule(userId, userEmail, updatedMessages).then(async (agentMsg) => {
      if (agentMsg) {
        if (agentMsg.metadata?.type === 'crisis_trigger') await handleCrisis();
        if (agentMsg.metadata?.type === 'task_assignment') setTasks(await db.getTasks(userEmail));
        if (agentMsg.metadata?.type === 'booking_confirmation') setSlots(await db.getSlots());
        setMessages(prev => [...prev, agentMsg]);
        await db.saveChatMessage(userId, agentMsg);
      }
    });
    setTimeout(() => setAvatarState('idle'), 3000);
  };

  const handleSend = async () => {
    if (!inputText.trim()) return;
    const textToSend = inputText;
    const userMsg: Message = { id: Date.now().toString(), role: 'user', text: textToSend, timestamp: new Date() };
    setMessages(prev => [...prev, userMsg]);
    setInputText('');
    setIsCloudSyncing(true);
    await db.saveChatMessage(userId, userMsg);
    setIsCloudSyncing(false);
    await processMessageSend(textToSend);
  };

  const toggleTask = async (id: string) => {
    setTasks(tasks.map(t => t.id === id ? { ...t, isCompleted: !t.isCompleted } : t));
    await db.toggleTaskCompletion(userEmail, id);
  };

  const handleBookSlot = (slot: AppointmentSlot) => {
    const hasActive = slots.some(s => (s.status === 'requested' || s.status === 'confirmed') && s.bookedByStudentId === userId);
    if (hasActive) {
      addNotification('You already have an upcoming session booked.', 'error');
      return;
    }
    setSelectedSlot(slot);
    setShowConsentModal(true);
  };

  const handleConsentSubmit = async (signature: string | File, mobile?: string) => {
    if (mobile) {
      // Directly save phone to Firestore without re-deriving User
      const { updateUserProfile } = await import('../services/userService');
      await updateUserProfile(user.id, { phone: mobile });
      setUser(prev => ({ ...prev, phone: mobile }));
    }
    if (!selectedSlot) return;
    let signatureData = '';
    if (signature instanceof File) {
      const reader = new FileReader();
      reader.readAsDataURL(signature);
      reader.onload = async () => { signatureData = reader.result as string; await completeBooking(signatureData); };
    } else { signatureData = signature; await completeBooking(signatureData); }
  };

  const completeBooking = async (signatureData: string) => {
    if (!selectedSlot) return;
    const consent: Omit<ConsentData, 'counselorSignature' | 'counselorSignDate' | 'counselorId' | 'counselorName'> = {
      slotId: selectedSlot.id, studentId: userId, studentName,
      studentSignature: signatureData, studentSignDate: new Date().toISOString(),
    };
    await db.saveConsent(consent as ConsentData);
    setIsCloudSyncing(true);
    const success = await firestoreRequestSlot(selectedSlot.id, userId, studentName);
    setIsCloudSyncing(false);
    if (success) {
      // subscribeToSlots will update slots list automatically on both student and counselor
      addNotification('Slot requested! Awaiting counselor approval.', 'success');
    } else {
      addNotification('Failed to book: This slot was just taken by someone else.', 'error');
    }
    setShowConsentModal(false);
    setSelectedSlot(null);
  };

  const handleCancelSlot = async (slotId: string) => {
    addNotification('Slot booking cancelled', 'info');
    setIsCloudSyncing(true);
    await firestoreUpdateSlotStatus(slotId, 'open');
    // subscribeToSlots will update the slot list automatically
    setIsCloudSyncing(false);
  };

  const handleProfileSave = (updatedUser: User) => {
    setUser(updatedUser);
    setShowProfileSettings(false);
  };

  const handleP2PSend = async () => {
    if (!p2pInput.trim()) return;

    // 1. Save message to DB
    await db.sendP2PMessage({ id: Date.now().toString(), senderId: userId, receiverId: 'counselor_dimple', text: p2pInput, timestamp: new Date().toISOString(), isRead: false });

    // 2. Clear input & Optimistically update UI
    const sentText = p2pInput;
    setP2PInput('');
    setP2PMessages(await db.getP2PThread(userId, 'counselor_dimple'));

    // 3. Background AI Crisis Detection
    detectCrisisInText(sentText).then(async (result) => {
      if (result.isCrisis) {
        console.warn('CRISIS DETECTED BY AI:', result.reason);
        triggerCrisis();
        // Optionally send an automated system message to the counselor alerting them immediately
        await db.sendP2PMessage({
          id: Date.now().toString() + '_sys',
          senderId: 'system',
          receiverId: 'counselor_dimple',
          text: `🚨 URGENT AI ALERT: Potential crisis detected for ${studentName}. Reason: ${result.reason}`,
          timestamp: new Date().toISOString(),
          isRead: false
        });
      }
    });
  };

  const openSlots = slots.filter(s => s.status === 'open');
  const generateChartData = (uid: string) => {
    const base = uid.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
    return [
      { name: 'Mon', stress: (base % 30) + 20 },
      { name: 'Tue', stress: (base % 40) + 40 },
      { name: 'Wed', stress: (base % 20) + 70 },
      { name: 'Thu', stress: ((base * 2) % 40) + 50 },
      { name: 'Fri', stress: ((base * 3) % 40) + 30 },
      { name: 'Sat', stress: ((base * 4) % 25) + 20 },
      { name: 'Sun', stress: (base % 15) + 15 },
    ];
  };
  const [chartData] = useState(() => generateChartData(userId));
  const notifColor = (type: string) =>
    type === 'success' ? 'bg-green-100 text-green-700 border-green-200' :
      type === 'error' ? 'bg-red-100 text-red-700 border-red-200' : 'bg-blue-100 text-blue-700 border-blue-200';

  return (
    <div className="min-h-screen flex flex-col bg-[#E6DDD0]">

      {/* ── Header ─────────────────────────────────────────────────────── */}
      <div className="w-full bg-[#DCD4C4] p-4 flex justify-between items-center shadow-md z-20">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-full bg-[#8A9A5B] flex items-center justify-center text-white font-bold text-xl">SU</div>
          <div>
            <h1 className="font-bold text-lg text-[#708090]">SpeakUp</h1>
            <p className="text-sm text-slate-500">Hi, {studentName}</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <div className="relative">
            <button onClick={async () => {
              setShowP2P(true);
              if (selectedCounselor) {
                await db.markThreadAsRead(userId, selectedCounselor.id);
                setUnreadP2P(0);
              }
            }} className="neu-icon-btn p-3 rounded-full text-[#708090]">
              <MessageSquare size={20} />
            </button>
            {unreadP2P > 0 && (
              <span className="absolute -top-1 -right-1 bg-blue-500 text-white text-[10px] w-5 h-5 flex items-center justify-center rounded-full animate-pulse border-2 border-[#DCD4C4]">
                {unreadP2P > 9 ? '9+' : unreadP2P}
              </span>
            )}
          </div>

          {/* Bell Dropdown */}
          <div className="relative" ref={bellRef}>
            <button onClick={() => { setShowBellDropdown(v => !v); if (!showBellDropdown) markAllRead(); }}
              className="neu-icon-btn p-3 rounded-full text-[#708090] relative">
              <Bell className="text-slate-500 hover:text-slate-800" size={20} />
              {unreadCount('student', userId) > 0 && (
                <span className="absolute -top-1 -right-1 bg-red-500 text-white text-[10px] w-5 h-5 flex items-center justify-center rounded-full animate-bounce border-2 border-[#DCD4C4]">
                  {unreadCount('student', userId) > 9 ? '9+' : unreadCount('student', userId)}
                </span>
              )}
            </button>
            {showBellDropdown && (
              <div className="absolute right-0 mt-2 w-80 bg-white rounded-xl shadow-2xl border border-slate-200 z-50 overflow-hidden">
                <div className="px-4 py-3 border-b border-slate-100 flex justify-between items-center bg-gray-50">
                  <span className="font-bold text-slate-700 text-sm">Notifications</span>
                  <button onClick={clearAll} className="text-xs text-red-500 hover:text-red-700 flex items-center gap-1"><Trash2 size={12} /> Clear all</button>
                </div>
                <div className="max-h-72 overflow-y-auto">
                  {storedNotifications.filter(n => !n.targetRole || (n.targetRole === 'student' && (!n.targetUserId || n.targetUserId === userId))).length === 0 ? (
                    <p className="text-center text-slate-400 text-sm py-8">No notifications yet</p>
                  ) : storedNotifications.filter(n => !n.targetRole || (n.targetRole === 'student' && (!n.targetUserId || n.targetUserId === userId))).map(n => (
                    <div key={n.id} className={`flex items-start gap-3 px-4 py-3 border-b border-slate-50 last:border-0 ${notifColor(n.type)} border-l-4`}>
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-medium leading-snug">{n.message}</p>
                        <p className="text-[10px] opacity-60 mt-0.5">{new Date(n.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</p>
                      </div>
                      <button onClick={() => clearOne(n.id)} className="flex-shrink-0 opacity-40 hover:opacity-80 mt-0.5"><X size={14} /></button>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          <ProfileDropdown
            user={user}
            onEditProfile={() => setShowProfileSettings(true)}
            onLogout={async () => {
              const { signOut } = await import('../services/authService');
              clearSParshHistory(userId);
              await signOut();
              onLogout?.();
            }}
          />
        </div>
      </div>

      <div className="flex flex-1 overflow-hidden">
        {/* Sidebar */}
        <div className="w-64 bg-[#DCD4C4] p-6 flex-col hidden md:flex">
          <div className="space-y-4">
            <button onClick={() => setActiveTab('home')} className={`w-full text-left px-4 py-3 rounded-lg transition-all flex items-center gap-3 ${activeTab === 'home' ? 'neu-pressed text-[#8A9A5B]' : 'text-slate-500 hover:bg-black/5'}`}><Home size={20} /> Home</button>
            <button onClick={() => setActiveTab('tasks')} className={`w-full text-left px-4 py-3 rounded-lg transition-all flex items-center gap-3 ${activeTab === 'tasks' ? 'neu-pressed text-[#8A9A5B]' : 'text-slate-500 hover:bg-black/5'}`}><CheckSquare size={20} /> Tasks</button>
            <button onClick={() => setActiveTab('booking')} className={`w-full text-left px-4 py-3 rounded-lg transition-all flex items-center gap-3 ${activeTab === 'booking' ? 'neu-pressed text-[#8A9A5B]' : 'text-slate-500 hover:bg-black/5'}`}><Calendar size={20} /> Slot Booking</button>
          </div>

          {/* Data Privacy Note */}
          <div className="mt-auto pt-6">
            <div className="p-3 bg-white/50 rounded-xl text-[10px] text-slate-400 leading-relaxed border border-slate-200">
              <p className="flex items-center gap-1 font-bold text-slate-500 mb-1"><Lock size={10} /> Privacy & Safety</p>
              <p>Data stays on this device. AI uses Google Gemini free API. Not used for ads or training. In a crisis: <strong className="text-red-500">iCall 9152987821</strong></p>
            </div>
          </div>
        </div>

        {/* API Error */}
        {apiError && (
          <div className="mx-4 mb-2 bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded-xl flex items-start gap-3 animate-in slide-in-from-top shadow-md">
            <Key size={20} className="mt-1 flex-shrink-0" />
            <div><h3 className="font-bold text-sm">Authentication Error</h3><p className="text-xs">The AI Token has expired or is invalid. Please update your <code>GEMINI_API_KEY</code>.</p></div>
          </div>
        )}

        {/* P2P Chat */}
        {showP2P && (
          <div className="absolute inset-0 z-40 bg-[#E6DDD0] flex flex-col animate-in slide-in-from-bottom duration-300">
            <div className="p-4 border-b border-gray-300 flex flex-col justify-center items-center bg-white/50 relative">
              <button onClick={() => setShowP2P(false)} className="absolute right-4 top-4 bg-white p-2 rounded-full shadow-sm hover:scale-105 transition-all"><XCircle className="text-slate-400 hover:text-red-500" size={24} /></button>
              <h3 className="font-black text-[#708090] text-lg">Chat with {selectedCounselor?.name ?? 'Counsellor'}</h3>
              <p className="text-xs text-slate-500 mb-3 font-medium">🛡️ End-to-End Encrypted</p>
              <button onClick={() => { setShowP2P(false); setShowCounselorPicker(true); }} className="px-4 py-2 bg-[#8A9A5B]/10 border border-[#8A9A5B]/30 shadow-sm rounded-xl text-sm text-[#8A9A5B] hover:bg-[#8A9A5B] hover:text-white transition-colors font-bold flex items-center gap-2">🔄 Switch Counsellor</button>
            </div>
            <div className="flex-1 overflow-y-auto p-4 space-y-3">
              {p2pMessages.map(m => (
                <div key={m.id} className={`flex ${m.senderId === userId ? 'justify-end' : 'justify-start'}`}>
                  <div className={`max-w-[80%] p-3 rounded-xl text-sm ${m.senderId === userId ? 'bg-[#8A9A5B] text-white' : 'bg-white text-slate-600'}`}>{m.text}</div>
                </div>
              ))}
              {p2pMessages.length === 0 && <p className="text-center text-slate-400 text-xs mt-10">Start a secure conversation with your counselor.</p>}
            </div>
            <div className="p-4 bg-white/50">
              <div className="flex gap-2">
                <input type="text" value={p2pInput} onChange={e => setP2PInput(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); handleP2PSend(); } }} placeholder="Type a message..." className="flex-1 p-2 rounded-lg border border-gray-300 outline-none" />
                <button onClick={handleP2PSend} className="bg-[#8A9A5B] text-white p-2 rounded-lg"><Send size={18} /></button>
              </div>
            </div>
          </div>
        )}

        {/* ── Main Content ───────────────────────────────────────────────── */}
        <div className="flex-1 p-6 overflow-hidden flex flex-col pb-20 md:pb-6">

          {/* ── HOME TAB ─────────────────────────────────────────────────── */}
          {activeTab === 'home' && (
            <div className="w-full h-full flex flex-col gap-4 overflow-y-auto pr-2 scrollbar-hide">

              {/* Follow-up nudge banner (only for prior bookers, 15+ days) */}
              {showFollowUpNudge && (
                <div className="flex-shrink-0 bg-[#f0fdf4] border border-[#8A9A5B]/40 rounded-2xl p-4 flex items-start gap-3 shadow-sm animate-in slide-in-from-top duration-500">
                  <span className="text-2xl">💚</span>
                  <div className="flex-1">
                    <p className="font-bold text-[#4a6741] text-sm">
                      {followUpDays >= 30 ? 'It\'s been a while — how have you been?' : 'Checking in on you'}
                    </p>
                    <p className="text-xs text-[#5a7a51] mt-0.5">
                      {followUpDays >= 30
                        ? 'It has been over a month since your last session. Would you like to book a follow-up? There\'s no pressure — we\'re here whenever you\'re ready.'
                        : 'It\'s been a couple of weeks. You don\'t have to wait until things feel overwhelming. Booking a check-in is always a good idea.'}
                    </p>
                    <button
                      onClick={() => setActiveTab('booking')}
                      className="mt-2 text-[11px] font-bold bg-[#8A9A5B] text-white px-3 py-1.5 rounded-lg hover:bg-[#76854d] transition-colors"
                    >
                      📅 Book a follow-up session
                    </button>
                  </div>
                  <button
                    onClick={() => {
                      const dismissUntil = new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString();
                      localStorage.setItem(`speakup_nudge_dismissed_${userId}`, dismissUntil);
                      setShowFollowUpNudge(false);
                    }}
                    className="text-[#8A9A5B] hover:text-[#4a6741] flex-shrink-0"
                  >
                    <X size={16} />
                  </button>
                </div>
              )}

              {/* Top Row: Environment Widget */}
              <div className="flex-shrink-0">
                <EnvironmentWidget variant="student" />
              </div>



              {/* Open Slots Strip or Upcoming Meeting Ribbon */}
              {(() => {
                const activeSlot = slots.find(s => (s.status === 'requested' || s.status === 'confirmed') && s.bookedByStudentId === userId);
                if (activeSlot) {
                  return (
                    <div className="flex-shrink-0 bg-[#E6DDD0] p-4 rounded-3xl border border-[#8A9A5B]/30 shadow-sm animate-in fade-in zoom-in-95">
                      <div className="flex justify-between items-center mb-2">
                        <h3 className="font-bold text-[#8A9A5B] flex items-center gap-2">
                          <Calendar size={16} /> Upcoming Meeting with Counsellor
                        </h3>
                        <span className={`text-[10px] uppercase font-bold px-2 py-0.5 rounded-full ${activeSlot.status === 'confirmed' ? 'bg-green-100 text-green-700' : 'bg-yellow-100 text-yellow-700'}`}>
                          {activeSlot.status}
                        </span>
                      </div>
                      <div className="flex items-center gap-3">
                        <div className="bg-white p-2 text-center rounded-xl min-w-[60px] shadow-sm flex flex-col items-center justify-center">
                          <p className="text-[10px] text-slate-400 font-bold uppercase leading-none mb-1">
                            {!isNaN(new Date(activeSlot.date).getTime()) ? new Date(activeSlot.date).toLocaleString('en-US', { weekday: 'short' }) : activeSlot.date.split(',')[0].slice(0, 3)}
                          </p>
                          <p className="font-black text-[#708090] text-lg leading-none">
                            {!isNaN(new Date(activeSlot.date).getTime()) ? new Date(activeSlot.date).getDate() : (activeSlot.date.split(' ')[1] || activeSlot.date.split(',')[0].slice(-2).replace(/[^0-9]/g, ''))}
                          </p>
                          <p className="text-[10px] text-[#8A9A5B] font-bold uppercase leading-none mt-1">
                            {!isNaN(new Date(activeSlot.date).getTime()) ? new Date(activeSlot.date).toLocaleString('en-US', { month: 'short' }) : activeSlot.date.split(' ').pop()}
                          </p>
                        </div>
                        <div>
                          <p className="font-bold text-[#708090] text-sm">{activeSlot.time}</p>
                          <p className="text-xs text-slate-500">{COUNSELORS.find(c => c.id === activeSlot.counselorId)?.name || 'Counsellor'}</p>
                        </div>
                      </div>
                    </div>
                  );
                }

                if (slots.filter(s => s.status === 'open').length > 0) {
                  return (
                    <div className="flex-shrink-0 bg-white/40 p-4 rounded-3xl border border-white/50">
                      <div className="flex justify-between items-center mb-3">
                        <h3 className="font-bold text-[#708090] flex items-center gap-2"><Calendar size={16} /> Available Counselling Slots</h3>
                        <button onClick={() => setActiveTab('booking')} className="text-[#8A9A5B] text-xs font-bold hover:underline">Book Now</button>
                      </div>
                      <div className="flex gap-3 overflow-x-auto scrollbar-hide pb-1">
                        {slots.filter(s => s.status === 'open').slice(0, 3).map(slot => (
                          <button key={slot.id} onClick={() => { handleBookSlot(slot); setActiveTab('booking'); }} className="flex-shrink-0 bg-white p-3 rounded-2xl shadow-sm border border-slate-100 min-w-[140px] text-left hover:scale-105 active:scale-95 transition-transform">
                            <p className="text-xs text-slate-400 font-bold uppercase">{slot.date}</p>
                            <p className="font-bold text-[#708090]">{slot.time}</p>
                            <p className="text-[10px] text-slate-500 truncate">{COUNSELORS.find(c => c.id === slot.counselorId)?.name || 'Counsellor'}</p>
                          </button>
                        ))}
                      </div>
                    </div>
                  );
                }
                return null;
              })()}

              {/* RAG Gamification Launchpad */}
              <div className="flex-shrink-0 bg-indigo-900/10 p-4 rounded-3xl border border-indigo-500/20 flex flex-col sm:flex-row justify-between items-center gap-4">
                <div>
                  <h3 className="font-bold text-indigo-900 flex items-center gap-2"><Sparkles size={16} /> Interactive Quests</h3>
                  <p className="text-xs text-indigo-800/70">Play gamified cognitive exercises crafted by your counselor.</p>
                </div>
                <button onClick={() => setOdyssey({ open: true, type: 'GAD7' })} className="bg-indigo-600 font-bold text-white px-5 py-2 rounded-xl text-sm shadow-md hover:bg-indigo-500 transition-colors whitespace-nowrap">
                  Open Quest Hub
                </button>
              </div>

              {/* Middle Row: Wellness Wall (Ribbon View) */}
              <div className="flex-shrink-0">
                <div className="flex items-center gap-2 mb-3">
                  <Newspaper size={18} className="text-[#8A9A5B]" />
                  <h3 className="font-bold text-[#708090] text-lg">Wellness Wall</h3>
                  <span className="text-xs bg-[#8A9A5B]/10 text-[#8A9A5B] px-2 py-0.5 rounded-full">From the Counselling Cell</span>
                </div>
                {posts.length === 0 ? (
                  <div className="bg-white/60 rounded-2xl p-6 text-center text-slate-400">
                    <Newspaper size={24} className="mx-auto mb-2 opacity-30" />
                    <p className="text-sm">No posts yet. Check back soon!</p>
                  </div>
                ) : (
                  <div className="flex gap-4 overflow-x-auto pb-2 scrollbar-hide snap-x">
                    {posts.map((post, idx) => (
                      <div key={post.id} className={`snap-start flex-shrink-0 ${idx === 0 ? 'w-[85%] md:w-[60%]' : 'w-[55%] md:w-[35%]'}`}>
                        <WallPostCard post={post} />
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Bottom Row: Tasks (Left) + Workload Meter (Right) Tiles */}
              <div className="flex-none grid grid-cols-2 gap-4 min-h-[160px]">
                {/* Tasks Column - Standard Gradient Tile */}
                <button onClick={() => setActiveTab('tasks')} className="bg-gradient-to-br from-indigo-500 to-purple-600 rounded-3xl p-6 flex flex-col items-center justify-center text-white shadow-lg transition-transform hover:scale-[1.02] active:scale-95 text-left h-full">
                  <CheckSquare size={32} className="mb-3 opacity-90" />
                  <h3 className="font-bold text-lg md:text-xl text-center mb-1">Wellness Quests</h3>
                  <p className="text-xs md:text-sm opacity-80 text-center">{tasks.filter(t => t.assignedBy !== 'system').length} Active Tasks · Tap</p>
                </button>

                {/* Workload Meter Column - Standard Gradient Tile */}
                <button onClick={() => { }} className="bg-gradient-to-br from-[#8A9A5B] to-[#76854d] rounded-3xl p-4 flex flex-col items-center text-white shadow-lg transition-transform hover:scale-[1.02] active:scale-95 text-left h-full group relative overflow-hidden">
                  <div className="flex justify-between items-center mb-2 flex-shrink-0 w-full relative z-10">
                    <h3 className="font-bold flex items-center gap-1.5 md:gap-2 text-sm md:text-base"><Activity size={16} /> Workload</h3>
                    <span className="text-[10px] bg-white/20 px-2 py-0.5 rounded-full">Peak Load</span>
                  </div>
                  <div className="flex-1 w-full mx-[-10px] mb-[-10px] relative z-10">
                    <ResponsiveContainer width="100%" height="100%">
                      <AreaChart data={chartData} margin={{ top: 5, right: 0, left: 0, bottom: 0 }}>
                        <Area type="monotone" dataKey="stress" stroke="#ffffff" fillOpacity={0.4} fill="#ffffff" />
                      </AreaChart>
                    </ResponsiveContainer>
                  </div>
                </button>
              </div>
            </div>
          )}

          {/* ── TASKS TAB ─────────────────────────────────────────────────── */}
          {activeTab === 'tasks' && (
            <div className="animate-in slide-in-from-bottom-10 duration-500 space-y-6">
              <h2 className="text-2xl font-bold text-[#708090]">Wellness Routines</h2>

              {/* ── Standard Quests (GAD-7 + BDI) — shown to all students ── */}
              <div>
                <div className="flex items-center gap-2 mb-3">
                  <Sword size={16} className="text-emerald-600" />
                  <h3 className="font-bold text-slate-600 text-base">Standard Quests</h3>
                  <span className="text-[10px] bg-emerald-100 text-emerald-700 px-2 py-0.5 rounded-full font-bold">Wellness Odyssey</span>
                </div>
                <div className="grid grid-cols-1 gap-4">
                  {/* GAD-7 Quest */}
                  <div className="bg-gradient-to-br from-indigo-900 via-slate-800 to-indigo-900 rounded-2xl p-5 border border-indigo-700/40 shadow-lg">
                    <div className="flex items-start justify-between">
                      <div>
                        <div className="text-2xl mb-1">🌀</div>
                        <h4 className="font-black text-white text-base">The Anxiety Realm</h4>
                        <p className="text-indigo-300 text-xs">GAD-7 · 7 Guardians · Up to 140 XP</p>
                        <p className="text-slate-400 text-xs mt-1">A brief survey measuring generalized anxiety symptoms.</p>
                      </div>
                      <button onClick={() => setOdyssey({ open: true, type: 'GAD7' })}
                        className="bg-emerald-500 hover:bg-emerald-400 text-black font-bold px-4 py-2 rounded-xl text-sm shadow-lg shadow-emerald-500/30 transition-all hover:scale-105 flex items-center gap-1.5">
                        <Map size={14} /> Begin
                      </button>
                    </div>
                  </div>

                  {/* BDI Quest */}
                  <div className="bg-gradient-to-br from-purple-900 via-slate-800 to-purple-900 rounded-2xl p-5 border border-purple-700/40 shadow-lg">
                    <div className="flex items-start justify-between">
                      <div>
                        <div className="text-2xl mb-1">🌑</div>
                        <h4 className="font-black text-white text-base">The Depression Depths</h4>
                        <p className="text-purple-300 text-xs">BDI-II · 21 Guardians · Up to 420 XP</p>
                        <p className="text-slate-400 text-xs mt-1">Beck's Depression Inventory — an evidence-based wellness check-in.</p>
                      </div>
                      <button onClick={() => setOdyssey({ open: true, type: 'BDI' })}
                        className="bg-emerald-500 hover:bg-emerald-400 text-black font-bold px-4 py-2 rounded-xl text-sm shadow-lg shadow-emerald-500/30 transition-all hover:scale-105 flex items-center gap-1.5">
                        <Map size={14} /> Begin
                      </button>
                    </div>
                  </div>
                </div>
              </div>

              {/* ── Custom Forged Quests ── */}
              {Object.keys(forgedGames).length > 0 && (
                <div>
                  <div className="flex items-center gap-2 mb-3 mt-6">
                    <Sparkles size={16} className="text-indigo-600" />
                    <h3 className="font-bold text-slate-600 text-base">Interactive Quests</h3>
                    <span className="text-[10px] bg-indigo-100 text-indigo-700 px-2 py-0.5 rounded-full font-bold">Custom Forged</span>
                  </div>
                  <div className="grid grid-cols-1 gap-4">
                    {Object.entries(forgedGames).map(([gameId, gameValue]) => {
                      const game = gameValue as GameMetadata;
                      return (
                        <div key={gameId} className="bg-gradient-to-br from-slate-800 to-indigo-950 rounded-2xl p-5 border border-indigo-700/40 shadow-lg">
                          <div className="flex items-start justify-between">
                            <div>
                              <div className="text-2xl mb-1">✨</div>
                              <h4 className="font-black text-white text-base">{game.title}</h4>
                              <p className="text-indigo-300 text-xs uppercase tracking-wide font-medium mt-1">{game.paradigm}</p>
                            </div>
                            <button onClick={() => setOdyssey({ open: true, type: gameId as any })}
                              className="bg-indigo-500 hover:bg-indigo-400 text-white font-bold px-4 py-2 rounded-xl text-sm shadow-lg shadow-indigo-500/30 transition-all hover:scale-105 flex items-center gap-1.5 mt-2">
                              <Map size={14} /> Begin
                            </button>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              )}

              {/* ── Counsellor-Assigned Tasks ── */}
              <div>
                <h3 className="font-bold text-slate-600 text-base mb-3">Assigned by Counsellor</h3>
                {tasks.filter(t => t.assignedBy !== 'system').length === 0 && (
                  <p className="text-center text-slate-400 text-sm py-4">No tasks assigned yet by your counsellor.</p>
                )}
                <div className="space-y-4">
                  {tasks.filter(t => t.assignedBy !== 'system').map(task => (
                    <div key={task.id} onClick={() => toggleTask(task.id)} className={`p-4 rounded-2xl flex items-center gap-4 transition-all cursor-pointer ${task.isCompleted ? 'neu-pressed opacity-60' : 'neu-flat'}`}>
                      <div className={`w-6 h-6 rounded-full border-2 flex items-center justify-center flex-shrink-0 ${task.isCompleted ? 'border-[#8A9A5B] bg-[#8A9A5B]' : 'border-slate-400'}`}>
                        {task.isCompleted && <CheckSquare size={14} className="text-white" />}
                      </div>
                      <div>
                        <h4 className={`font-bold ${task.isCompleted ? 'text-slate-400 line-through' : 'text-[#708090]'}`}>{task.title}</h4>
                        <p className="text-xs text-slate-400">Assigned by {task.assignedBy}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* Consent Modal */}
          {showConsentModal && selectedSlot && (
            <ConsentForm role="student" studentName={studentName} program="PGDM"
              onClose={() => setShowConsentModal(false)} onSubmit={handleConsentSubmit} user={user} />
          )}
          {showProfileSettings && (
            <ProfileSettingsModal user={user} onClose={() => setShowProfileSettings(false)} onSave={handleProfileSave} />
          )}

          {/* ── BOOKING TAB ───────────────────────────────────────────────── */}
          {activeTab === 'booking' && (
            <div className="animate-in slide-in-from-right-10 duration-500 space-y-4">
              <h3 className="text-xl font-bold text-[#708090] mb-2">Book a Sanctuary Slot</h3>
              <p className="text-xs text-slate-400 mb-5">Slots are published by your counselor. Tap "Book" to request — they'll confirm shortly.</p>

              {slots.length === 0 ? (
                <div className="flex flex-col items-center justify-center py-12 text-slate-400 neu-flat rounded-2xl">
                  <Calendar size={36} className="mb-3 opacity-30" />
                  <p className="font-bold text-slate-500 mb-1">No slots published yet</p>
                  <p className="text-xs text-center">Your counselor hasn't added any sessions. Check back soon.</p>
                </div>
              ) : slots.map(slot => {
                const isMyBooking = slot.bookedByStudentId === userId;
                const isOpen = slot.status === 'open';
                const isRequested = slot.status === 'requested';
                const isConfirmed = slot.status === 'confirmed';

                return (
                  <div key={slot.id} className={`rounded-2xl p-4 border transition-all ${isMyBooking && isConfirmed ? 'bg-green-50 border-green-200' :
                    isMyBooking && isRequested ? 'bg-amber-50 border-amber-200' :
                      isOpen ? 'neu-flat border-transparent' :
                        'bg-gray-50 border-gray-200 opacity-60'
                    }`}>
                    <div className="flex justify-between items-start gap-3">
                      <div className="flex-1">
                        <div className="font-bold text-[#708090]">{slot.counselorName}</div>
                        <div className="text-sm text-slate-400 mt-0.5">{slot.date} · {slot.time}</div>
                        {/* Status badge */}
                        <div className="mt-2">
                          {isMyBooking && isConfirmed && (
                            <span className="inline-flex items-center gap-1 bg-green-100 text-green-700 text-[11px] font-bold px-2.5 py-1 rounded-full">
                              ✓ Confirmed — see you then!
                            </span>
                          )}
                          {isMyBooking && isRequested && (
                            <span className="inline-flex items-center gap-1 bg-amber-100 text-amber-700 text-[11px] font-bold px-2.5 py-1 rounded-full">
                              ⏳ Awaiting counselor approval
                            </span>
                          )}
                          {!isMyBooking && !isOpen && (
                            <span className="text-[11px] text-slate-400 italic">Booked by another student</span>
                          )}
                        </div>
                      </div>

                      <div className="flex flex-col items-end gap-2 flex-shrink-0">
                        {/* Download consent — confirmed only */}
                        {isMyBooking && isConfirmed && (
                          <button
                            onClick={() => downloadConsentAsPDF(slot.id)}
                            className="flex items-center gap-1 text-xs text-gray-500 hover:text-gray-700 bg-gray-100 hover:bg-gray-200 px-3 py-1.5 rounded-xl transition-colors"
                          >
                            <Download size={13} /> Consent
                          </button>
                        )}
                        {/* Book / Cancel / Disabled */}
                        {isOpen && (
                          <button
                            onClick={() => handleBookSlot(slot)}
                            className="px-4 py-2 rounded-xl text-sm font-bold bg-[#8A9A5B] text-white hover:bg-[#76854d] transition-all active:scale-95 shadow-sm"
                          >
                            Book
                          </button>
                        )}
                        {isMyBooking && isRequested && (
                          <button
                            onClick={() => handleCancelSlot(slot.id)}
                            className="px-4 py-2 rounded-xl text-sm font-bold bg-amber-500 hover:bg-amber-600 text-white transition-all active:scale-95"
                          >
                            Cancel Request
                          </button>
                        )}
                        {isMyBooking && isConfirmed && (
                          <span className="text-[10px] text-slate-400 italic text-right max-w-[120px]">
                            Message counselor to cancel
                          </span>
                        )}
                        {!isOpen && !isMyBooking && (
                          <button disabled className="px-4 py-2 rounded-xl text-sm font-bold bg-gray-200 text-gray-400 cursor-not-allowed">
                            Taken
                          </button>
                        )}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>

      {/* ── Medical Disclaimer Strip ─────────────────────────────────────── */}
      <div className="bg-amber-50 border-t border-amber-200 px-4 py-2 text-[10px] text-amber-700 text-center hidden md:block">
        <ShieldAlert size={11} className="inline mr-1" />
        <strong>Wellness Tool Only:</strong> SParsh is not a doctor or clinical tool. For urgent help: <strong>iCall 9152987821</strong> (Mon–Sat 8am–10pm) • <strong>Vandrevala Foundation: 1860-2662-345</strong> (24/7)
      </div>

      {/* ── Floating Chat Button ──────────────────────────────────────────── */}
      <div className="fixed bottom-8 right-8 z-30">
        <button onClick={() => setShowCounselorPicker(true)} className="w-16 h-16 rounded-full bg-[#8A9A5B] flex items-center justify-center shadow-lg text-white animate-pulse">
          <Heart size={32} fill="white" />
        </button>
      </div>

      {/* ── Chat Window ───────────────────────────────────────────────────── */}
      {isChatOpen && (
        <div className="fixed bottom-24 right-4 md:right-8 w-full max-w-[92vw] sm:max-w-96 h-[65vh] max-h-[550px] bg-white/95 backdrop-blur-md rounded-2xl shadow-2xl flex flex-col z-50 animate-in slide-in-from-bottom-10 duration-500 border border-slate-200">
          <div className="p-3 border-b flex justify-between items-center bg-[#8A9A5B]/10 rounded-t-2xl">
            <div className="flex items-center gap-2">
              <span className="font-bold text-[#708090]">SParsh AI</span>
              <span className="flex items-center gap-1 text-[10px] text-slate-400 bg-white/70 px-2 py-0.5 rounded-full border border-slate-200">
                <Lock size={9} /> Free API · Locally Encrypted
              </span>
            </div>
            <button onClick={() => setIsChatOpen(false)} className="text-slate-400 hover:text-slate-600"><XCircle size={18} /></button>
          </div>

          {/* Privacy notice banner */}
          <div className="px-4 py-2 bg-amber-50 border-b border-amber-100 text-[10px] text-amber-700 flex items-start gap-2">
            <ShieldAlert size={12} className="mt-0.5 flex-shrink-0" />
            <span>SParsh is a <strong>wellness companion</strong>, not a medical professional. For clinical support, please see a doctor.</span>
          </div>

          <div className="flex-1 overflow-y-auto p-4 space-y-4 scrollbar-hide">
            {messages.map(msg => (
              <div key={msg.id} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                <div className={`max-w-[85%] p-3 rounded-xl text-sm ${msg.role === 'user' ? 'bg-[#8A9A5B] text-white' : 'bg-gray-100 text-slate-700'}`}>
                  {msg.text}
                  {/* Inline slot booking cards */}
                  {msg.role !== 'user' && msg.metadata?.type === 'booking_suggestion' && openSlots.length > 0 && (
                    <div className="mt-3 space-y-2">
                      <p className="text-xs font-bold text-slate-500 uppercase tracking-wide">Available Slots</p>
                      {openSlots.slice(0, 3).map(slot => (
                        <div key={slot.id} className="bg-white rounded-lg p-2.5 border border-[#8A9A5B]/30 flex justify-between items-center gap-2 shadow-sm">
                          <div>
                            <p className="text-xs font-bold text-[#708090]">{slot.counselorName}</p>
                            <p className="text-[11px] text-slate-400">{slot.date} · {slot.time}</p>
                          </div>
                          <button onClick={() => { handleBookSlot(slot); setIsChatOpen(false); }}
                            className="text-xs bg-[#8A9A5B] text-white px-3 py-1.5 rounded-lg font-bold hover:bg-[#76854d] transition-colors flex-shrink-0">
                            Book Now
                          </button>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            ))}
            {isLoading && <div className="text-center text-xs text-slate-400 animate-pulse">SParsh is listening...</div>}
            <div ref={messagesEndRef} />
          </div>

          <div className="p-4 border-t border-slate-100 flex flex-col gap-3">
            {/* Quick actions row */}
            <div className="flex gap-2 overflow-x-auto scrollbar-hide pb-1">
              <button
                onClick={() => setShowChatSlotPicker(v => !v)}
                className="whitespace-nowrap bg-[#8A9A5B]/10 hover:bg-[#8A9A5B]/20 text-[#8A9A5B] text-[11px] px-3 py-1.5 rounded-full border border-[#8A9A5B]/30 transition-colors font-bold flex items-center gap-1.5 flex-shrink-0"
              >
                📅 Book a Session
              </button>
              {["Feeling stressed", "Is my privacy secure?"].map(prompt => (
                <button key={prompt} onClick={() => { setInputText(prompt); processMessageSend(prompt); }}
                  className="whitespace-nowrap bg-gray-100 hover:bg-gray-200 text-slate-600 text-[11px] px-3 py-1.5 rounded-full border border-gray-200 transition-colors flex-shrink-0">
                  {prompt}
                </button>
              ))}
            </div>

            {/* In-chat slot picker */}
            {showChatSlotPicker && (
              <div className="bg-[#f8f6f1] rounded-xl border border-[#8A9A5B]/20 p-3 space-y-2 max-h-44 overflow-y-auto">
                <p className="text-[11px] font-bold text-[#708090] uppercase tracking-wide">Available Slots — tap to book</p>
                {slots.filter(s => s.status === 'open').length === 0 ? (
                  <p className="text-xs text-slate-400 text-center py-2">No open slots right now. Check back soon.</p>
                ) : (
                  slots.filter(s => s.status === 'open').map(slot => (
                    <div key={slot.id} className="flex items-center justify-between bg-white rounded-lg p-2.5 border border-slate-100 shadow-sm">
                      <div>
                        <p className="text-xs font-bold text-[#708090]">{slot.counselorName}</p>
                        <p className="text-[11px] text-slate-400">{slot.date} · {slot.time}</p>
                      </div>
                      <button
                        onClick={() => {
                          setShowChatSlotPicker(false);
                          handleBookSlot(slot);
                        }}
                        className="text-xs bg-[#8A9A5B] text-white px-3 py-1.5 rounded-lg font-bold hover:bg-[#76854d] transition-colors"
                      >
                        Select
                      </button>
                    </div>
                  ))
                )}
              </div>
            )}

            <div className="flex gap-2">
              <input type="text" value={inputText} onChange={(e) => setInputText(e.target.value)}
                onKeyDown={(e) => { if (e.key === 'Enter' && inputText.trim()) { handleSend(); } }} placeholder="Speak to SParsh..."
                className="flex-1 p-2 rounded-lg border border-gray-200 outline-none text-sm" />
              <button disabled={!inputText.trim()} onClick={handleSend} className="bg-[#8A9A5B] disabled:bg-[#8A9A5B]/50 text-white p-2 rounded-lg transition-colors"><Send size={18} /></button>
            </div>
          </div>
        </div>
      )}

      {/* Mobile Bottom Nav */}
      <div className="md:hidden fixed bottom-0 left-0 w-full bg-[#DCD4C4] border-t border-gray-300 p-2 flex justify-around items-center z-20">
        <button onClick={() => setActiveTab('home')} className={`p-2 rounded-full ${activeTab === 'home' ? 'text-[#8A9A5B]' : 'text-slate-500'}`}><Home size={24} /></button>
        <button onClick={() => setActiveTab('tasks')} className={`p-2 rounded-full ${activeTab === 'tasks' ? 'text-[#8A9A5B]' : 'text-slate-500'}`}><CheckSquare size={24} /></button>
        <button onClick={() => setActiveTab('booking')} className={`p-2 rounded-full ${activeTab === 'booking' ? 'text-[#8A9A5B]' : 'text-slate-500'}`}><Calendar size={24} /></button>
      </div>

      {/* ── Counselor Picker Modal ──────────────────────────────────────── */}
      {showCounselorPicker && (
        <div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center p-6 backdrop-blur-sm">
          <div className="bg-white rounded-3xl shadow-2xl p-6 w-full max-w-sm animate-in zoom-in-95 duration-300">
            <h3 className="text-lg font-bold text-[#708090] mb-1">Who would you like to talk to?</h3>
            <p className="text-xs text-slate-400 mb-5">Your conversations are secure and private 🔒</p>
            <div className="space-y-3">
              <button onClick={() => { setShowCounselorPicker(false); setIsChatOpen(true); }}
                className="w-full flex items-center gap-4 p-4 rounded-2xl border border-indigo-100 bg-indigo-50/50 hover:border-indigo-300 hover:bg-indigo-50 transition-all text-left">
                <div className="w-12 h-12 rounded-full bg-indigo-500 flex items-center justify-center text-white font-bold flex-shrink-0"><Sparkles size={20} /></div>
                <div>
                  <p className="font-bold text-indigo-900">SParsh AI</p>
                  <p className="text-xs text-indigo-500">24/7 Wellness Companion</p>
                </div>
              </button>
              {COUNSELORS.map(c => (
                <button key={c.id} onClick={async () => {
                  setSelectedCounselor(c);
                  setShowCounselorPicker(false);
                  setShowP2P(true);
                  setP2PMessages(await db.getP2PThread(userId, c.id));
                }}
                  className="w-full flex items-center gap-4 p-4 rounded-2xl border border-slate-200 hover:border-[#8A9A5B] hover:bg-[#8A9A5B]/5 transition-all text-left">
                  <div className="w-12 h-12 rounded-full bg-[#8A9A5B] flex items-center justify-center text-white font-bold flex-shrink-0">{c.avatar}</div>
                  <div>
                    <p className="font-bold text-slate-700">{c.name}</p>
                    <p className="text-xs text-slate-400">{c.specialization}</p>
                  </div>
                </button>
              ))}
            </div>
            <button onClick={() => setShowCounselorPicker(false)} className="mt-4 w-full text-center text-sm text-slate-400 hover:text-slate-600">Cancel</button>
          </div>
        </div>
      )}

      {/* ── Wellness Odyssey Modal ──────────────────────────────────────── */}
      {odyssey.open && (
        <div className="fixed inset-0 z-[100] bg-black/50 backdrop-blur-sm flex items-center justify-center p-4 md:p-6 overflow-hidden animate-in fade-in zoom-in-95 duration-300">
          <div className="w-full max-w-md h-[80vh] max-h-[700px] bg-slate-900 shadow-2xl rounded-3xl overflow-hidden relative border border-slate-600/50">
            <WellnessOdyssey
              surveyType={odyssey.type}
              userId={userId}
              onClose={() => setOdyssey(prev => ({ ...prev, open: false }))}
            />
          </div>
        </div>
      )}

      {/* ── Onboarding Tour ─────────────────────────────────────────────────── */}
      {showOnboarding && (
        <OnboardingTour
          onComplete={(playGame) => {
            localStorage.setItem(`speakup_onboarding_${userId}`, 'true');
            setShowOnboarding(false);
            if (playGame) {
              setOdyssey({ open: true, type: 'GAD7' });
            }
          }}
        />
      )}

      {/* ── How It Works Overlay (Feature 6) ─────────────────────────────────── */}
      {showHowItWorks && (
        <div className="fixed inset-0 z-[200] bg-black/50 backdrop-blur-sm flex items-center justify-center p-3 md:p-6 animate-in fade-in duration-200">
          <div className="w-full max-w-lg bg-[#f8f6f1] rounded-3xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh] animate-in zoom-in-95 duration-300">
            {/* Header */}
            <div className="bg-[#8A9A5B]/10 border-b border-[#8A9A5B]/20 p-5 flex justify-between items-start">
              <div>
                <h2 className="text-xl font-black text-[#708090]">How It Works</h2>
                <p className="text-xs text-slate-500 mt-1">Everything you need to know before your first session</p>
              </div>
              <button onClick={() => { setShowHowItWorks(false); setHowItWorksSection(null); }} className="p-2 bg-white rounded-full shadow-sm text-slate-400 hover:text-red-500 transition-all">
                <X size={18} />
              </button>
            </div>

            {/* Accordion sections */}
            <div className="overflow-y-auto flex-1 p-4 space-y-3">
              {[
                {
                  icon: '📅',
                  title: 'Step-by-step Booking Process',
                  content: `1. Go to 'Slot Booking' tab or tap a slot card on the home screen\n2. Select an available slot showing your counselor's name, date, and time\n3. You'll be asked to complete a short digital consent form — this replaces the paper form usually signed during the first session\n4. After you submit, the slot status changes to 'Awaiting Counsellor Approval'\n5. Ms. Dimple Wagle or Ms. Jyoti Sangle will confirm or reschedule via the app\n6. You'll receive a Bell notification when your slot is confirmed\n7. You can cancel a pending request at any time before confirmation`,
                },
                {
                  icon: '🤝',
                  title: 'What to Expect in a Session',
                  content: `Each session is approximately 45 minutes and conducted in private.\n\nFirst sessions typically cover:\n• Understanding your current situation\n• Discussing what prompted you to seek support\n• Explaining how ongoing sessions would work\n\nSubsequent sessions are guided by you — you set the pace. The counsellor will never push you to share more than you're ready to.\n\nSessions are supportive, not evaluative. Nothing discussed is reported on your academic record.`,
                },
                {
                  icon: '🔒',
                  title: 'Confidentiality & When It May Be Broken',
                  content: `Everything you share in a session is confidential. This means:\n• No information is shared with faculty, parents, or other students\n• Session notes are kept offline by the counsellor — they are NOT stored in this app\n• The app only records: booking slots you request, consent form data, and wellness task completion\n\nConfidentiality may only be broken if:\n• There is a serious and immediate risk to your life or someone else's safety\n• Required by a court of law\n\nIn all other situations, what you share stays with your counsellor.`,
                },
                {
                  icon: '🛡️',
                  title: 'Data Privacy',
                  content: `SPeakUp is designed privacy-first:\n• All chat data and personal messages are encrypted before being stored\n• Data stays on this device (localStorage) — it is not sent to any cloud database\n• The SParsh AI chat history is automatically cleared when you log out\n• Your P2P chats with the counsellor are stored separately and persist across sessions\n• No analytics, advertising platforms, or third parties ever access your data\n• The AI model (Qwen2.5-7B) processes text in-flight and does not retain it`,
                },
                {
                  icon: '📝',
                  title: 'What Is Recorded — and What Is Not',
                  content: `WHAT IS STORED IN THE APP:\n✓ Your slot booking requests and confirmed slots\n✓ Your digital consent form (encrypted)\n✓ Wellness tasks assigned by your counsellor\n✓ Your GAD-7 / BDI-II assessment scores (for your own trend view only)\n✓ Your SParsh AI chat (within the current session only — deleted on logout)\n\nWHAT IS NOT STORED:\n✗ Session notes or clinical observations (these remain in the counsellor's offline diary)\n✗ Audio or video recordings\n✗ Mood data without your action\n✗ Any data shared with institutional management, faculty, or parents`,
                },
              ].map((section, i) => (
                <div key={i} className="bg-white rounded-2xl border border-slate-100 shadow-sm overflow-hidden">
                  <button
                    onClick={() => setHowItWorksSection(howItWorksSection === i ? null : i)}
                    className="w-full flex items-center justify-between p-4 text-left hover:bg-slate-50 transition-colors"
                  >
                    <span className="flex items-center gap-3 font-bold text-[#708090]">
                      <span className="text-xl">{section.icon}</span>
                      <span className="text-sm">{section.title}</span>
                    </span>
                    <span className="text-[#8A9A5B] flex-shrink-0">
                      {howItWorksSection === i ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
                    </span>
                  </button>
                  {howItWorksSection === i && (
                    <div className="px-4 pb-4 text-sm text-slate-600 leading-relaxed whitespace-pre-line border-t border-slate-50 pt-3">
                      {section.content}
                    </div>
                  )}
                </div>
              ))}
            </div>

            <div className="p-4 border-t border-slate-100 text-center">
              <p className="text-[10px] text-slate-400">Questions not answered here? Chat with SParsh or message your counselor directly. 💚</p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default StudentDashboard;